Remove activity dependency
Baseflow/flutter-geolocator pull request #1016
Opened 2022-03-26 17:19 UTC by Wackymax

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Bug fix

### :arrow_heading_down: What is the current behavior?

Currently when someone tries to obtain a position update stream from a different flutter engine that isn't attached to an activity an error is returned and the location updates aren't being returned.

### :new: What is the new behavior (if this is a feature change)?

This PR introduces changes that allows the geolocator foreground service to bind to the application context instead of an activity which will allow other flutter background libraries to start the service from the background in absence of an Android activity. This also now determine wether to to use our own foreground service or to just start the location updates in the service asking for the position stream.

### :boom: Does this PR introduce a breaking change?

No

### :bug: Recommendations for testing

The position stream will now behave differently depending on whether foreground notification config has been provided. If not then a position stream is created like it used to before the foreground service was introduced, if it is provided the the foreground service is used instead for the position updates. I've introduced log messages to indicate this distinction. Other libraries like `flutter_foreground_task` should also work correctly now where a new flutter engine is created and bound to this plugin.

### :memo: Links to relevant issues/docs

https://github.com/Baseflow/flutter-geolocator/issues/1012

### :thinking: Checklist before submitting

- [X] I made sure all projects build.
- [X] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [X] I updated the relevant documentation.
- [X] I rebased onto current `master`.

2022-03-29 10:25 UTC, cheeco83 commented
Wackymax, I tried to implement your changes. Unfortunately, I get the same "Foreground task has not started correctly" is still there.

But I might have made a mistake getting your updated github commit. In the Pubspec.yaml, I added the following lines and ran pub upgrade geolocator afterwards. I am not sure if I have the right commit hash, as there were three this day.

  geolocator:
    git:
      url: https://github.com/Wackymax/flutter-geolocator.git
      ref: 06379fd  # commit hash
      path: geolocator/

2022-03-30 05:36 UTC, Wackymax commented
@mvanbeusekom can you kick off the validations again? Looks like something went wrong during the build process.

2022-03-31 13:54 UTC, Wackymax commented
Done 😊 

> On 31 Mar 2022, at 15:09, Maurits van Beusekom ***@***.***> wrote:
> 
> ﻿
> Hi @Wackymax,
> 
> After some investigation it turns out the GitHub no longer allows accessing a repo through the git protocol (git://) in an unauthenticated way and instead suggests to use the HTTP protocol. Turns out all our example apps have a dependency on a Baseflow template which we access via a git reference (using the git protocol) and this was blocking / failing the build process.
> 
> I have just merged an update, could you please rebase your branch on the latest master and push the update? After that the build should run fine again. Thanks and sorry for the delay.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

2022-03-31 14:10 UTC, mvanbeusekom requested changes
Hi @Wackymax,

Thank you for this pull request, looks very good. I just have two small remarks, would appreciate it if you could have a look.

2022-03-31 14:10 UTC, mvanbeusekom commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/GeolocatorPlugin.java
> +    geolocatorPlugin.bindForegroundService(registrar.activity());
I am aware this is all deprecated but non the less it might be better to use the `registrar.activeContext()` in this case. The `activeContext()` method will return the `activity` if it's available and otherwise will return the Application's context (official documentation can be found [here](https://api.flutter.dev/javadoc/io/flutter/plugin/common/PluginRegistry.Registrar.html#activeContext())).
```suggestion
    locationServiceHandler.setContext(registrar.activeContext());
    geolocatorPlugin.bindForegroundService(registrar.activeContext());
```

2022-03-31 19:14 UTC, mvanbeusekom approved these changes
Thank you for the update! LGTM

2022-03-31 19:28 UTC, merged