LINUX: Linux Native implementantion, Open GNOME Location Settings in GNOME anda Improove GNOME detection
Baseflow/flutter-geolocator pull request #1140
Opened 2022-09-29 19:17 UTC by thiagotognoli

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
feature

### :arrow_heading_down: What is the current behavior?
Unsupported

### :new: What is the new behavior (if this is a feature change)?
Open GNOME Location Settings in GNOME

### :boom: Does this PR introduce a breaking change?
no

### :bug: Recommendations for testing

### :memo: Links to relevant issues/docs

### :thinking: Checklist before submitting

- [ x] I made sure all projects build.
- [ x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [ x] I updated CHANGELOG.md to add a description of the change.
- [ x] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [ x] I updated the relevant documentation.
- [ x] I rebased onto current `master`.

2022-10-11 20:39 UTC, pablojimpas commented
I had planned to iterate on the current Linux implementation, but I'm glad to see someone else has done so :)

What do you think of this changes @jpnurmi? I don't have a GNOME desktop at hand to test it properly, but at least the previous functionality still works on my setup.

2022-10-12 10:00 UTC, jpnurmi commented on geolocator_linux/linux/geolocator_linux_plugin.cc
> +    // response = FL_METHOD_RESPONSE(fl_method_success_response_new(result));
clean up

2022-10-12 10:00 UTC, jpnurmi commented on geolocator_linux/linux/include/geolocator_linux/geolocator_linux_plugin.h
> +// gboolean openLocationPanel() {
clean up

2022-10-12 10:01 UTC, jpnurmi commented on geolocator_linux/test/geolocator_gnome_test.dart
> +    // verify(settings.get('enabled')).called(1);
?

2022-10-12 10:02 UTC, jpnurmi commented on geolocator_linux/test/geolocator_linux_method_channel_test.dart
> +  test('getPlatformVersion', () async {
update

2022-10-12 12:39 UTC, pablojimpas commented
Based on @jpnurmi comments, I'll suggest against following the approach of this PR and try to implement the same functionality with the existing `dbus.dart` package. That way, we will avoid using native code since it adds a bunch of unnecessary complexity and needs more platform expertise to be properly implemented & maintained.

2022-10-12 13:04 UTC, thiagotognoli commented
Hi @pablojimpas, my first attempt was using dbus, but I didn't find a solution.
@jpnurmi if you know how or could someone help me please?
I believe that sooner or later native code will be necessary and every bridge has already been created for this, just implementing new functionality when necessary.
About cleaning the code really needs to be clean, if they intend to approve the PR I will do it.

2022-10-12 13:13 UTC, thiagotognoli commented on geolocator_linux/lib/src/geolocator_linux.dart
> +class FactoryToGeolocatorLinuxRegister {
@jpnurmi for that I would have to increase the code complexity and decrease the performance, because both the Platform.enviroment and GeoClueManager are not constants, and the default value of an optional parameter must be constant.
So it would have to accept null values in these parameters and test them if null instantiate them.

2022-10-12 15:47 UTC, jpnurmi commented on geolocator_linux/lib/src/geolocator_linux.dart
> +class FactoryToGeolocatorLinuxRegister {
> increase the code complexity

i'm not sure i understand how passing in optional arguments, which would be only made visible for testing, would increase the complexity compared to a factory registry

> decrease the performance

keep in mind that registerWith() is called _once_ during the life-time of a flutter application

2022-10-12 17:53 UTC, thiagotognoli commented
Thank you @jpnurmi, was implemented!

2022-10-14 08:55 UTC, jpnurmi commented
ping @mvanbeusekom

2022-10-14 09:01 UTC, jpnurmi commented on geolocator_linux/lib/src/geolocator_linux.dart
> +class FactoryToGeolocatorLinuxRegister {
```dart
MockFactoryToGeolocatorLinuxRegister mockFactoryToGeolocatorLinuxRegister =
    MockFactoryToGeolocatorLinuxRegister();

when(mockFactoryToGeolocatorLinuxRegister.makeManager())
    .thenReturn(MockGeoClueManager());

when(mockFactoryToGeolocatorLinuxRegister.getPlatformEnvironment())
    .thenReturn({
  'XDG_CURRENT_DESKTOP': ...,
  'GNOME_SHELL_SESSION_MODE': ...,
});

await GeolocatorLinux.registerWith(mockFactoryToGeolocatorLinuxRegister);
expect(GeolocatorPlatform.instance, isA<GeolocatorGnome>());
```

vs.

```dart
await GeolocatorLinux.registerWith(
  manager: MockGeoClueManager(),
  environment: {
    'XDG_CURRENT_DESKTOP': ...,
    'GNOME_SHELL_SESSION_MODE': ...,
  },
);
expect(GeolocatorPlatform.instance, isA<GeolocatorGnome>());
```

2022-10-14 09:04 UTC, jpnurmi commented on geolocator_linux/example/linux/flutter/generated_plugins.cmake
> +
we can revert these changes that were caused by the earlier native plugin (not sure why the flutter app template doesn't just ignore these generated files...)

2022-10-14 09:08 UTC, jpnurmi commented on geolocator_linux/lib/src/geolocator_gnome.dart
> +            name: 'org.gnome.ControlCenter',
was it renamed? it's `org.gnome.Settings` in my system
```
org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.ControlCenter was not provided by any .service files
```

2022-10-14 09:10 UTC, mvanbeusekom requested changes
Thanks for making this contribution.

As I am not familiar with Linux, I am going to trust @jpnurmi and @pablojimpas advise on the implementation details.

I do however have two small style related issues that would be nice if you could fix them.

2022-10-14 09:10 UTC, mvanbeusekom commented on geolocator_linux/AUTHORS
> +Thiago Tognoli <dev@togger.com.br>
nit: missing new line at the end of file (we try to stay POSIX compatible).
```suggestion
Thiago Tognoli <dev@togger.com.br>

```

2022-10-14 09:10 UTC, mvanbeusekom commented on geolocator_linux/CHANGELOG.md
> +- Open Location Settings implementation in GNOME SHELL
Spelling mistake in `Improovement`, maybe update this to (to stick with Google's [CHANGELOG style](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style) guidelines):
```suggestion
- Improves GNOME detection.
- Adds the ability to open Location Settings in GNOME SHELL.
```

2022-10-14 09:27 UTC, jpnurmi commented on geolocator_linux/lib/src/geolocator_gnome.dart
> +            name: 'org.gnome.ControlCenter',
https://gitlab.gnome.org/GNOME/gnome-control-center/-/merge_requests/1153

try the new `org.gnome.Settings` first and if it fails, fall back to the old `org.gnome.ControlCenter`?

2022-10-14 14:39 UTC, pablojimpas requested changes

2022-10-14 14:39 UTC, pablojimpas commented on geolocator_linux/.gitignore
> +migrate_working_dir/
This should be removed, comes from the migration process from package to plugin than later was reverted.

2022-10-14 14:39 UTC, pablojimpas commented on geolocator_linux/.metadata
> +    - 'ios/Runner.xcodeproj/project.pbxproj'
The same goes for this file, was automatically modified by the migration tool. I think it should be restored to the previous state.

2022-10-14 14:39 UTC, pablojimpas commented on geolocator_linux/example/linux/flutter/generated_plugins.cmake
> +endforeach(ffi_plugin)
The same comment that jpnurmi made above

2022-10-14 16:55 UTC, thiagotognoli commented on geolocator_linux/lib/src/geolocator_gnome.dart
> +            name: 'org.gnome.ControlCenter',
thank you, i am using ubuntu 22.04

2022-10-18 19:59 UTC, thiagotognoli reviewed
Hi @mvanbeusekom , @pablojimpas and @jpnurmi its all ok ?

2022-10-27 17:29 UTC, thiagotognoli commented
> reviewer

Hi @mvanbeusekom, its all done, can review please

2022-10-27 17:38 UTC, jpnurmi reviewed
could you do one more round of clean-ups and revert all the unrelated or unnecessary template changes, please?

2022-10-27 17:38 UTC, jpnurmi commented on geolocator_linux/.metadata
> +    - 'ios/Runner.xcodeproj/project.pbxproj'
Not resolved?

2022-10-27 17:38 UTC, jpnurmi commented on geolocator_linux/example/.metadata
> +project_type: package
revert

2022-10-27 17:38 UTC, jpnurmi commented on geolocator_linux/example/linux/flutter/generated_plugins.cmake
> +endforeach(plugin)
revert

2022-10-27 17:38 UTC, jpnurmi commented on geolocator_linux/lib/src/geolocator_linux.dart
> +class FactoryToGeolocatorLinuxRegister {
unused

2022-10-27 17:38 UTC, jpnurmi commented on geolocator_linux/test/geoclue_x_test.dart
> +    //     equals(GeoClueAccuracyLevel.none));
?

2022-10-28 03:56 UTC, thiagotognoli commented on geolocator_linux/.metadata
> +    - 'ios/Runner.xcodeproj/project.pbxproj'
I had confused the example's .metadata with the plugin's. both ok now. thank you.

2022-10-28 03:57 UTC, thiagotognoli commented
> could you do one more round of clean-ups and revert all the unrelated or unnecessary template changes, please?

I think everything is ok. thank you.

2022-11-08 18:28 UTC, thiagotognoli commented
> could you do one more round of clean-ups and revert all the unrelated or unnecessary template changes, please?

hi @jpnurmi . is everything ok? please help me with the approval of this PR.

2023-05-15 12:18 UTC, mvanbeusekom approved these changes
LGTM, thank you very much for this contribution.

2023-05-15 12:18 UTC, merged