Implement allowBackgroundLocationUpdates iOS setting
Baseflow/flutter-geolocator pull request #1155
Opened 2022-10-20 10:18 UTC by landyrev

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Feature

### :arrow_heading_down: What is the current behavior?
Currently geolocator sets `allowBackgroundLocationUpdates` equal to `true` by default when the `UIBackgroundModes` contains `location` value inside the app's Info.plist, which leads to `Geolocator.getPositionStream` receiving background geolocations even if you don't need them

### :new: What is the new behavior (if this is a feature change)?
User can disable background geolocations updates even if their app contains `location` value inside the `UIBackgroundModes` key

### :boom: Does this PR introduce a breaking change?
No, `allowBackgroundLocationUpdates` is set to true by default

### :bug: Recommendations for testing
Can be tested on iOS devices and simulators
1. Add `location` value to the `UIBackgroundModes` Info.plist key
2. Request position stream with `getPositionStream` with `locationSettings` equal to:
```dart
AppleSettings(
  allowBackgroundLocationUpdates: false
)
```
3. Send app to the background 
4. Check that there is no background geolocation indicator visible in status bar

### :thinking: Checklist before submitting

- [x] I made sure all projects build.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [x] I updated the relevant documentation.
- [x] I rebased onto current `master`.

2022-10-28 07:43 UTC, mvanbeusekom requested changes
Thank you for contributing, this looks very good. I have just one request to add an additional test.

2022-10-28 07:43 UTC, mvanbeusekom commented on geolocator_apple/ios/Classes/Handlers/GeolocationHandler.m
> +      && [GeolocationHandler shouldEnableBackgroundLocationUpdates];
There should be a unit test to verify the `allowsBackgroundLocationUpdates` property is set correctly (only when both values are true.

2022-10-31 07:43 UTC, landyrev commented on geolocator_apple/ios/Classes/Handlers/GeolocationHandler.m
> +      && [GeolocationHandler shouldEnableBackgroundLocationUpdates];
@mvanbeusekom good point, thanks! Added a couple of tests for that

2022-10-31 12:54 UTC, mvanbeusekom approved these changes
LGTM, thanks for this great addition.

2022-10-31 12:54 UTC, merged

2022-11-16 05:32 UTC, Faiizii commented
I think it should be in readme file. I implemented the background location updates in one of my app. In the recent updates it stopped working with the following code 
```
Geolocator.getPositionStream(
          locationSettings: LocationSettings(
              accuracy: LocationAccuracy.bestForNavigation,
          )
      )
```

I have ignored the rest of the params for testing purpose. 

When I replaced the location settings with Apple Setting for iOS as suggested above, background location updates are working.

```
AppleSettings(
            accuracy: LocationAccuracy.bestForNavigation,
            allowBackgroundLocationUpdates: true,
            showBackgroundLocationIndicator: true,
            activityType: ActivityType.automotiveNavigation
        );
``` 

I have followed all the steps like allowing location updates in background mode, always location permission.

2022-11-16 05:53 UTC, landyrev commented
hey, @Faiizii, what's your `geolocator_apple` version? (you can find it in the `pubspec.lock`) 

Also, do you use the `getCurrentPosition` somewhere in your code? If yes, then it might be related to this issue: https://github.com/Baseflow/flutter-geolocator/pull/1169

2022-11-16 05:56 UTC, Faiizii commented
`geolocator_apple` is 2.2.3. No, I've just used the `getPositionStream` to get continuous updates.

2022-11-16 12:35 UTC, mvanbeusekom commented
Hi @landyrev, 

Reading the original comment from @Faiizii, it seems that the only problem is that the documentation doesn't explain to use the `AppleSettings` and specifically set the `allowBackgroundLocationUpdates` parameter to `true` if you'd want to enable background support for iOS.

He originally used the `LocationSettings` object which is mentioned in the documentation but doesn't turn on support for background services (as this is Apple specific).

2022-11-16 12:51 UTC, landyrev commented
@mvanbeusekom, ah, right. We set allowBackgroundLocationUpdates equal to `true` only when you use `AppleSettings`.

Yeah, fair enough, I'll draft a PR