Fix: iOS location manager background geolocation settings overridden by getCurrentPosition
Baseflow/flutter-geolocator pull request #1169
Opened 2022-11-09 08:59 UTC by landyrev

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Bug fix

### :arrow_heading_down: What is the current behavior?
When you request positions stream with `Geolocator.getPositionStream` and `showBackgroundLocationIndicator` or `allowBackgroundLocationUpdates` set to `true` and then request the current position with `Geolocator.getCurrentPosition`, you get the iOS location manager settings (`showBackgroundLocationIndicator` and `allowBackgroundLocationUpdates`) set back to `false`.

### :new: What is the new behavior (if this is a feature change)?
Calling `Geolocator.getCurrentPosition` is not affecting `showBackgroundLocationIndicator` and `allowBackgroundLocationUpdates` while listening for position updates.

### :boom: Does this PR introduce a breaking change?
No

### :bug: Recommendations for testing
1. Start listening for background updates with `Geolocator.getPositionStream` and `allowBackgroundLocationUpdates` and `allowBackgroundLocationUpdates` set to `true`
2. Request current position with `Geolocator.getCurrentPosition`
3. Send the app to the background
4. Check if background indicator is active

### :memo: Links to relevant issues/docs

### :thinking: Checklist before submitting

- [x] I made sure all projects build.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [x] I updated the relevant documentation.
- [x] I rebased onto current `master`.

2022-11-20 20:27 UTC, mvanbeusekom requested changes

2022-11-20 20:27 UTC, mvanbeusekom commented on geolocator_apple/ios/Classes/Handlers/GeolocationHandler.m
> +@property(assign, nonatomic) bool isBackgroundGeolocationAllowed;
This property seems to be added, but I don't really see where it is being used. Am I missing something?

2022-12-11 11:53 UTC, landyrev commented
Hey, @mvanbeusekom! I think this PR is ready to be merged

2023-01-26 13:46 UTC, mvanbeusekom approved these changes
LGTM

2023-01-26 13:46 UTC, merged

2023-01-26 13:50 UTC, mvanbeusekom commented
Thanks for this contribution, I have just published version 2.2.5 of the `geolocator_apple` package which contains these fixes.