[macos] Fix GeolocatorApple plugin registration
Baseflow/flutter-geolocator pull request #1173
Opened 2022-11-16 12:52 UTC by passsy

2022-11-16 12:59 UTC, passsy reviewed
Fix indentation

2022-11-16 13:31 UTC, jxstxn1 commented on .github/workflows/geolocator_apple.yaml
> +      xcodebuild-destination: "platform=iOS Simulator,OS=16,name=iPhone 14"
```suggestion
      xcodebuild-destination: "platform=iOS Simulator,OS=16.0,name=iPhone 14"
```
This should fix the IOS Test

2022-11-16 16:00 UTC, mvanbeusekom requested changes
This looks good, could you also update the `pubspec.yaml` and `CHANGELOG.md` files in each of the packages affected?

2022-11-16 20:57 UTC, passsy commented
Sure @mvanbeusekom 👍

2022-11-20 20:22 UTC, mvanbeusekom approved these changes
LGTM

2022-11-20 20:22 UTC, merged