Update and rename b-bug-report.md to b-bug-report.yml
Baseflow/flutter-geolocator pull request #1269
Opened 2023-06-06 14:49 UTC by JeroenWeener

Updates the bug report template to use GitHub Forms and make it easier for issuers to fill in an issue.

2023-06-07 09:52 UTC, mvanbeusekom requested changes
Very good start thanks. I have added some suggestions which I think makes the template a little bit better.

2023-06-07 09:52 UTC, mvanbeusekom commented on .github/ISSUE_TEMPLATE/b-bug-report.yml
> +description: You encountered a bug in the geolocator plugin that you would like to report.
Can we describe a bit more detailed what is considered a "bug"? How about something like this:
```suggestion
description: You encountered a bug in the geolocator plugin resulting in application crashes, compilation errors or invalid/ unexpected results.
```

2023-06-07 09:52 UTC, mvanbeusekom commented on .github/ISSUE_TEMPLATE/b-bug-report.yml
> +      - label: iOS
This should list all supported platforms:
```suggestion
      - label: Android
      - label: iOS
      - label: Linux
      - label: macOS
      - label: Web
      - label: Windows
```

2023-06-07 09:52 UTC, mvanbeusekom commented on .github/ISSUE_TEMPLATE/b-bug-report.yml
> +        To effectively tackle it, we require as much information as possible.
Since we are asking a lot of information, lets try to really persuade users to be as complete as possible: 

```suggestion
        To effectively tackle it, we require as much information as possible. This might seem a lot of information but 
        will allow us to quickly help you and resolve the issue you are facing.
```

2023-06-07 09:52 UTC, mvanbeusekom commented on .github/ISSUE_TEMPLATE/b-bug-report.yml
> +
I'd really like to include the extra note asking issue reporters not to upload screenshots of text:

```suggestion
        Please create a minimal reproducible sample that shows the problem
        and attach it below between the lines with the backticks.
        
        Note: Please do not upload screenshots of text. Instead, use code blocks
        or the above mentioned ways to upload your code sample.
```

2023-06-07 09:52 UTC, mvanbeusekom commented on .github/ISSUE_TEMPLATE/b-bug-report.yml
> +        </details>
Request the version of the plugin in which the issue occurs:
```suggestion
        </details>
  - type: input
    id: version
    attributes:
      label: Version
      description: In which version of the geolocator plugin does the bug occur?
      placeholder: ex. 1.2.3
      validations:
        required: true
```

2023-06-07 09:52 UTC, mvanbeusekom commented on .github/ISSUE_TEMPLATE/b-bug-report.yml
> +title: "Bug: "
nit: common convention seems to be to add square brackets around the `Bug` keyword. Not sure if this has additional benefits though.

```suggestion
title: "[Bug]: "
```

2023-06-07 09:52 UTC, mvanbeusekom commented on .github/ISSUE_TEMPLATE/b-bug-report.yml
> +      - label: I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues)
```suggestion
      - label: I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
      - label: I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.
```

2023-06-07 11:38 UTC, andreisas06 commented on .github/ISSUE_TEMPLATE/b-bug-report.yml
> +        Please provide the full output of running `flutter doctor -v`
```suggestion
        Please provide the full output of running `flutter doctor -v`.
```

2023-06-08 10:19 UTC, andreisas06 commented on .github/ISSUE_TEMPLATE/b-bug-report.yml
> +      description: Please tell us what is expected to happen.
Maybe it sounds a bit more professional, I am not sure, just a suggestion.

2023-06-08 10:20 UTC, andreisas06 commented on .github/ISSUE_TEMPLATE/b-bug-report.yml
> +      description: Please tell us what is actually happening.
```suggestion
      description: Please provide a description of the current behavior.
```

2023-06-08 10:26 UTC, andreisas06 commented on .github/ISSUE_TEMPLATE/b-bug-report.yml
> +      description: Please tell us exactly how to reproduce the problem you are running into.
```suggestion
      description: Please provide specific steps to reproduce the issue.
```

2023-06-08 10:27 UTC, JeroenWeener commented on .github/ISSUE_TEMPLATE/b-bug-report.yml
> +      description: Please tell us what is expected to happen.
```suggestion
      description: Please provide a description of the expected behavior.
```

2023-06-14 13:58 UTC, mvanbeusekom approved these changes
LGTM

2023-06-14 13:58 UTC, merged