Fix inaccurate location readings
Baseflow/flutter-geolocator pull request #1324
Opened 2023-09-13 13:16 UTC by JeroenWeener

Users have reported that locations have an wildly low accuracy on Android 13 since `geolocator_android: 4.2.3`. This seems to be caused by the fact that a different location provider is returned from `getBestProvider()`. Instead of the fused or gps provider, the network provider is used. To remedy this, this PR replaces the use of `getBestProvider()` with a custom implementation that returns the most accurate location provider. Note that `getBestProvider()` will be deprecated starting from API 34 anyway, with no clear replacement. Additionally, the `LocationManagerCompat` class and its associates are used to indicate a `LocationRequestCompat.Quality` to the OS.

Closes #1114.

## Pre-launch Checklist

- [x] I made sure the project builds.
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is does not need version changes.
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I rebased onto `main`.
- [ ] I added new tests to check the change I am making, or this PR does not need tests.
- [x] I made sure all existing and new tests are passing.
- [x] I ran `dart format .` and committed any changes.
- [x] I ran `flutter analyze` and fixed any errors.

[Contributor Guide]: https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

2023-09-13 13:25 UTC, mvanbeusekom requested changes
Looks good however, I think we should also handle the `PASSIVE_PROVIDER` when the support `LocationAccuracy` is set to `lowest`. See also my comments.

2023-09-13 13:25 UTC, mvanbeusekom commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/location/LocationManagerClient.java
> +          case lowest:
I think `lowest` should return `LocationRequestCompat.PASSIVE_INTERVAL`:

```suggestion
          case lowest:
                  return LocationRequestCompat.PASSIVE_INTERVAL;
```

2023-09-13 13:25 UTC, mvanbeusekom commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/location/LocationManagerClient.java
> +  private static @Nullable String getBestProvider(@NonNull LocationManager locationManager) {
I think we should pass in the `LocationAccuracy` as well and if the supplied value equals `LocationAccuracy.lowest` immediately return `LocationManager.PASSIVE_PROVIDER`:

```suggestion
  private static @Nullable String getBestProvider(@NonNull LocationManager locationManager, @NonNull LocationAccuracy accuracy) {
      if (accuracy == LocationAccuracy.lowest) {
          return LocationManager.PASSIVE_PROVIDER;
      }
      
```

2023-09-13 15:12 UTC, JeroenWeener commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/location/LocationManagerClient.java
> +  private static @Nullable String getBestProvider(@NonNull LocationManager locationManager) {
I agree with using the `PASSIVE_PROVIDER` on `lowest`. I did not put the logic in this method, as I feel it does not belong there. Instead, I added it to `startPositionUpdates`.

2023-09-13 19:28 UTC, mvanbeusekom requested changes

2023-09-13 19:28 UTC, mvanbeusekom commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/location/LocationManagerClient.java
> +  private static @Nullable String getBestProvider(@NonNull LocationManager locationManager) {
I think it should be in this method, there should only be one place which determines the provider. This will ensure we always use the same logic when we need to determine the provider on multiple places. 

Maybe we should however rename the method as I agree that the name `getBestProvider` doesn't fit well with the `PASSIVE_PROVIDER`. So lets rename it to `getProvider` or `determineProvider`.

2023-09-13 19:28 UTC, mvanbeusekom commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/location/LocationManagerClient.java
> +          case lowest:
Why do you think this is not a quality parameter? According to the [documentation](https://developer.android.com/reference/androidx/core/location/LocationRequestCompat#PASSIVE_INTERVAL()) the `LocationRequestCompat.PASSIVE_PROVIDER` is a valid quality parameter with the const value  of `9223372036854775807 `.

2023-09-13 19:28 UTC, mvanbeusekom commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/location/LocationManagerClient.java
> +        : getBestProvider(this.locationManager);
The logic to determine the provider should al be encapsulated in one method (as mentioned in my other comment). Splitting it up like this will increase the change of mistakes when the provider needs to be determined on multiple places in the code.

2023-09-13 19:31 UTC, mvanbeusekom commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/location/LocationManagerClient.java
> +          case lowest:
You are correct, I miss read the documentation. This should be good the way it is.

2023-09-14 06:48 UTC, mvanbeusekom commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/location/LocationManagerClient.java
> +      quality = accuracyToQuality(accuracy);
Rereading the [documentation](https://developer.android.com/reference/androidx/core/location/LocationRequestCompat#PASSIVE_INTERVAL()), we should use the `PASSIVE_INTERVAL` here when the `LocationAccuracy` is set to lowest:

```suggestion
      accuracy = locationOptions.getAccuracy();
      distanceFilter = locationOptions.getDistanceFilter();
      quality = accuracyToQuality(accuracy);
      timeInterval = (accuracy == LocationAccurracy.lowest) 
          ? LocationRequestCompat.PASSIVE_INTERVAL 
          : locationOptions.getTimeInterval();
```

2023-09-14 08:02 UTC, merged