(chore): Update dependencies
Baseflow/flutter-geolocator pull request #1347
Opened 2023-09-29 09:37 UTC by Zazo032

*Replace this paragraph with a short description of what issue this pull request (PR) solves and provide a description of the change.  Consider including before/after screenshots.*

*List at least one fixed issue.*

## Pre-launch Checklist

- [ ] I made sure the project builds.
- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is does not need version changes.
- [ ] I updated `CHANGELOG.md` to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I rebased onto `main`.
- [ ] I added new tests to check the change I am making, or this PR does not need tests.
- [ ] I made sure all existing and new tests are passing.
- [ ] I ran `dart format .` and committed any changes.
- [ ] I ran `flutter analyze` and fixed any errors.

[Contributor Guide]: https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

2023-09-29 09:41 UTC, Zazo032 commented
Platform tests are failing because examples depend on the updated and unreleased `geolocator_platform_interface: ^4.2.0`. Should I make them depend on `4.1.0` instead?

2023-09-29 11:40 UTC, mvanbeusekom commented
Hi @Zazo032, 

Thank you for contributing and helping out. Normally we'd split these kind of PRs up in one PR per package, builds will then automatically start succeeding when the platform interface package is released.

Some small notes:
- I noticed that you bumped the version number with a minor update. Since this is only a dependency update, I think a patch update is sufficient.
- When adding an entry to the CHANGELOG we try to adhere to the style guide documented here: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style. Would you mind updating this as well?

2023-09-29 17:54 UTC, mvanbeusekom requested changes
Looks good, with minor point according style of changelog entry

2023-09-29 17:54 UTC, mvanbeusekom commented on geolocator_platform_interface/CHANGELOG.md
> +- Update dependencies
Current entry isn't quite according to the [style guide](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style). How about:

```suggestion
- Updates dependencies to latest versions to prevent conflicts with other packages.
```

2023-10-02 07:58 UTC, mvanbeusekom approved these changes
LGTM

2023-10-02 07:58 UTC, merged