`geolocator_android`: Update dependencies
Baseflow/flutter-geolocator pull request #1350
Opened 2023-10-03 13:41 UTC by Zazo032

- Updates dependencies to latest versions to prevent conflicts with other packages.
- Updates Android Gradle Plugin to version 8.
- Updates `compileSdk` version to `34`.

Follow-up of https://github.com/Baseflow/flutter-geolocator/pull/1347

https://github.com/Baseflow/flutter-geolocator/issues/1348

## Pre-launch Checklist

- [ ] I made sure the project builds.
- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is does not need version changes.
- [ ] I updated `CHANGELOG.md` to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I rebased onto `main`.
- [ ] I added new tests to check the change I am making, or this PR does not need tests.
- [ ] I made sure all existing and new tests are passing.
- [ ] I ran `dart format .` and committed any changes.
- [ ] I ran `flutter analyze` and fixed any errors.

[Contributor Guide]: https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

2023-10-04 08:24 UTC, mvanbeusekom requested changes
Thanks for the contribution. I do have one concern about updating to Gradle 8, could you address that please?

2023-10-04 08:24 UTC, mvanbeusekom commented on geolocator_android/example/android/app/build.gradle
> +    compileSdkVersion 34
Shouldn't this also be renamed to `compileSdk` (similar to the changes in the `android/build.gradle` file)?

2023-10-04 08:24 UTC, mvanbeusekom commented on geolocator_android/example/android/app/build.gradle
> +        targetSdkVersion 34
Shouldn't this also be renamed to `targetSdk` (similar to the changes in the `android/build.gradle` file)?

2023-10-04 08:24 UTC, mvanbeusekom commented on geolocator_android/android/build.gradle
> +        classpath 'com.android.tools.build:gradle:8.1.2'
I am a bit reluctant about upgrading to gradle 8+ since Flutter stable is still on gradle 7.3.0. 

My worry is that because we upgrade, apps consuming our plugin are also forced to upgrade. In my experience, Gradle (and it's configuration) is a mystery to most Flutter developers and I am afraid upgrading to early will lead to a lot of questions and irritation.

2023-10-04 11:41 UTC, Zazo032 commented on geolocator_android/android/build.gradle
> +        classpath 'com.android.tools.build:gradle:8.1.2'
Where did you check the Gradle version in the latest Flutter stable? I can revert this part if it could lead to other issues

2023-10-04 19:31 UTC, mvanbeusekom commented on geolocator_android/android/build.gradle
> +        classpath 'com.android.tools.build:gradle:8.1.2'
What I usually do is create a fresh Flutter project using the latest stable version (e.g. `flutter create --platforms=android -a java test`) and then check the gradle version used there.

This is also what most developers do and what Google will support in case of issues.

2024-01-29 15:20 UTC, emakar commented
Is something holding this from being merged?

2024-05-16 07:44 UTC, mvanbeusekom commented
Closing this PR as it is a bit outdated and comments regarding my concerns have not been addressed. 

Recent attempts to update Android Gradle Plugin showed breaking changes for users still depending on AGP 7.0 or below. Flutter officially supports AGP 7.0 and higher as mentioned also in the recent [release description for Flutter 3.22](https://medium.com/flutter/whats-new-in-flutter-3-22-fbde6c164fe3):

>Flutter tool enforces version requirements on Gradle, AGP, Java, and Kotlin
In this release, the Flutter tool enforces a policy regarding the versions that it supports for Gradle, the Android Gradle Plugin (AGP), Java, and Kotlin. Initially, the tool only provides warnings.
>
>Currently, the supported version ranges are as follows:
>
>Gradle — Fully supported 7.0.2 to current, warn otherwise
AGP — Fully supported 7.0.0 to current, warn otherwise
Java — Fully supported Java 11 to current, warn otherwise
Kotlin — Fully supported 1.5.0 to current, warn otherwise

2024-05-16 07:44 UTC, closed without merging