Refactor Geolocator Android
Baseflow/flutter-geolocator pull request #1352
Opened 2023-10-09 20:49 UTC by vbuberen

Updates for Android part to modernise and improve compatibility.

- Removed code related to pre 1.12 Flutter Android embedding as it is not supported by recent Flutter versions and min Flutter of geolocator plugin is higher anyway, so no need to save compatibility.
- Removed unused file
- Removed Jetifier as it is not needed in projects that use AndroidX dependencies and because it affects build speed: https://adambennett.dev/2020/08/disabling-jetifier/
- Switched to `ContextCompat` function for broadcast receiver declaration as there were missing flags:
<img width="821" alt="Screenshot 2023-10-09 at 18 44 36" src="https://github.com/Baseflow/flutter-geolocator/assets/13467769/7f0e5415-fe51-451e-9f2a-6a7bf2f28e24">

## Pre-launch Checklist

- [x] I made sure the project builds.
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is does not need version changes.
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I rebased onto `main`.
- [x] I added new tests to check the change I am making, or this PR does not need tests.
- [x] I made sure all existing and new tests are passing.
- [x] I ran `dart format .` and committed any changes.
- [x] I ran `flutter analyze` and fixed any errors.

[Contributor Guide]: https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

2023-10-11 09:42 UTC, mvanbeusekom requested changes
Hi, 

Thank you very much for this contribution. We are very happy with the changes but have two small styling issues that we would appreciate at fix for.

2023-10-11 09:42 UTC, mvanbeusekom commented on geolocator_android/CHANGELOG.md
> +- Registers
Changelog entries should confirm to the changelog style guide, would you mind updating this to something like this:

```suggestion
- Removes deprecated support for Android V1 embedding from the JAVA code base. Note that the geolocator's Flutter restrictions already require the use of a Flutter version that doesn't support V1 embedding anymore.
```

2023-10-11 09:42 UTC, mvanbeusekom commented on geolocator_android/example/android/gradle.properties
> +android.useAndroidX=true
Nit: missing an empty line at the end of the document.

2023-10-11 11:21 UTC, vbuberen commented on geolocator_android/CHANGELOG.md
> +- Registers
Yes, sure. In fact it seems I didn't commit latest changes for changelogs 🤦🏻‍♂️ , so will do it including your feedback.

2023-10-11 11:44 UTC, vbuberen commented on geolocator_android/CHANGELOG.md
> +- Registers
Updated

2023-10-11 11:44 UTC, vbuberen commented on geolocator_android/example/android/gradle.properties
> +android.useAndroidX=true
Updated

2023-10-26 08:05 UTC, vbuberen commented
@mvanbeusekom Would like to remind about this PR as I have addressed your feedback, but see that you already released 4.3.2 of the plugin.

2023-10-26 16:07 UTC, mvanbeusekom approved these changes
LGTM, thank you for this contribution

2023-10-26 16:07 UTC, merged