Feature/gnss satellites in view
Baseflow/flutter-geolocator pull request #1364
Opened 2023-10-31 07:52 UTC by TimHoogstrate

*Replace this paragraph with a short description of what issue this pull request (PR) solves and provide a description of the change.  Consider including before/after screenshots.*

*List at least one fixed issue.*

## Pre-launch Checklist

- [ ] I made sure the project builds.
- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is does not need version changes.
- [ ] I updated `CHANGELOG.md` to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I rebased onto `main`.
- [ ] I added new tests to check the change I am making, or this PR does not need tests.
- [ ] I made sure all existing and new tests are passing.
- [ ] I ran `dart format .` and committed any changes.
- [ ] I ran `flutter analyze` and fixed any errors.

[Contributor Guide]: https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

2023-11-02 14:26 UTC, mvanbeusekom requested changes
Have some small points, but looks really good.

2023-11-02 14:26 UTC, mvanbeusekom commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/location/LocationMapper.java
> +        }
nit: This formatting seems a little bit off, can you format the java code with google-java-format plugin for Android Studio (or IntelliJ)?

2023-11-02 14:26 UTC, mvanbeusekom commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/location/NmeaClient.java
> +                        ++gnss_satellites_used_in_fix;
Can you use braces here (as per [Google Java Style guide](https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used))?

```suggestion
                for (int i = 0; i < gnss_satellite_count; ++i) {
                    if (status.usedInFix(i)) {
                        ++gnss_satellites_used_in_fix;
                    }
                }
```

2023-11-02 14:26 UTC, mvanbeusekom commented on geolocator_android/lib/src/types/android_position.dart
> +      {required this.satelliteCount,
nit: small formatting mistake:

```suggestion
  const AndroidPosition({
      required this.satelliteCount,
```

2023-11-02 14:26 UTC, mvanbeusekom commented on geolocator_android/lib/src/types/android_position.dart
> +      isMocked = false})
nit: add comma after last parameter so `dart format .` will automatically apply correct formatting:

```suggestion
      isMocked = false,
    })
```

2023-11-02 14:26 UTC, mvanbeusekom commented on geolocator_android/lib/src/types/android_position.dart
> +
Remove empty line:
```suggestion
```

2023-11-06 13:49 UTC, TimHoogstrate commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/location/LocationMapper.java
> +        }
changed the formatting

2023-11-06 13:53 UTC, mvanbeusekom approved these changes
LGTM

2024-01-22 08:54 UTC, merged

2024-01-28 05:19 UTC, Wackymax commented
@mvanbeusekom I don't think this was tested at all before merging. The AndroidPosition class zeroes out all the values and the the equals method is flawed checking only the new properties