chore: allow arm64 simulator
Baseflow/flutter-geolocator pull request #1405
Opened 2024-01-05 19:09 UTC by 4rthurmonteiro

*Replace this paragraph with a short description of what issue this pull request (PR) solves and provide a description of the change.  Consider including before/after screenshots.*

*List at least one fixed issue.*

## Pre-launch Checklist

- [ ] I made sure the project builds.
- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is does not need version changes.
- [ ] I updated `CHANGELOG.md` to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I rebased onto `main`.
- [ ] I added new tests to check the change I am making, or this PR does not need tests.
- [ ] I made sure all existing and new tests are passing.
- [ ] I ran `dart format .` and committed any changes.
- [ ] I ran `flutter analyze` and fixed any errors.

[Contributor Guide]: https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

2024-01-05 19:49 UTC, mvanbeusekom requested changes
Hi,

Thank you very much for this PR . I haven only one small request regarding the style of the CHANGELOG message. If you could address that I would be happy to land this PR.

2024-01-05 19:49 UTC, mvanbeusekom commented on geolocator_apple/CHANGELOG.md
> +* Iphonesimulator arm64 as valid architecture.
As for our `CHANGELOG` style we try to follow the guidelines specified by Google (as described [here](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style)).

In other words, would you mind rephrasing this to something in the lines of:

```
* Allows the ARM64 architecture as a valid IPhone simulator architecture.
```

2024-01-05 20:42 UTC, 4rthurmonteiro commented on geolocator_apple/CHANGELOG.md
> +* Iphonesimulator arm64 as valid architecture.
Thank you!

2024-01-08 13:34 UTC, 4rthurmonteiro commented
@mvanbeusekom i updated the PR

2024-01-08 13:49 UTC, mvanbeusekom approved these changes
LGTM! Thanks for this contribution.

2024-01-08 13:49 UTC, merged