migrates geolocator_web to package:web
Baseflow/flutter-geolocator pull request #1475
Opened 2024-04-02 02:03 UTC by josh-burton

This PR migrates from dart:html to package:web and js_interop.

A few notes/questions:
- I've increased the dart/flutter sdk versions in geolocator_web in order to use js_interop. I'm unsure if we need to bump these versions in the other geolocator packages as well.
- Mockito can no longer be used with the new js_interop types (at least I ran into errors with it being unable to generate mocks).
- The package:web geolocation methods now require a timeout value, rather than allowing null. Infinity is the value for timeouts in the html geolocation api, but passing double.infinity.toInt as timeout throws an error that this is an invalid value when invoked in javascript. Instead of defaulted to a timeout of 1 day, but this needs more input.

## Pre-launch Checklist

- [x] I made sure the project builds.
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is does not need version changes.
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I rebased onto `main`.
- [x] I added new tests to check the change I am making, or this PR does not need tests.
- [x] I made sure all existing and new tests are passing.
- [x] I ran `dart format .` and committed any changes.
- [x] I ran `flutter analyze` and fixed any errors.

[Contributor Guide]: https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

2024-05-15 07:53 UTC, mvanbeusekom requested changes
Hi @josh-burton,

Sorry for the delay and thank you for creating this PR. In general the changes look good, I have made a few small remarks which would be great if you can address those.

2024-05-15 07:53 UTC, mvanbeusekom commented on geolocator_web/lib/src/html_permissions_manager.dart
> +    return toLocationPermission(status?.state);
This will result in an exception when the `status` parameter is `null` (this might happen when the user dismisses the permission dialog without specifically granting or denying the permission). 

In these cases the permission request should always return the `denied` permission, informing the user to request permission again.

I think it would be good to use a similar construct as the old statement:
```suggestion
    return status != null
            ? toLocationPermission(status.state)
            : LocationPermission.denied;
```

2024-05-15 07:53 UTC, mvanbeusekom commented on geolocator_web/CHANGELOG.md
> +- Migrates to Dart SDK 3.3.0 and Flutter 3.16.0.
nit: officially the bullets should be indented with two spaces for the correct markdown behaviour:
```suggestion
  - Migrates from dart:html to package:web and dart:js_interop
  - Migrates to Dart SDK 3.3.0 and Flutter 3.16.0.
```

2024-05-15 07:53 UTC, mvanbeusekom commented on geolocator_web/lib/src/html_geolocation_manager.dart
> +      completer.completeError(e);
Please convert the error to one of the custom exceptions defined in the `convertPositionError` method before completing the completer. 

This will throw a known exception to the application developers so they don't have to update their application logic and handle unexpected exceptions solely for the geolocator_web plugin.

2024-05-15 08:37 UTC, josh-burton commented on geolocator_web/lib/src/html_geolocation_manager.dart
> +      completer.completeError(e);
I've returned a platform exception so the caught exception can be passed to the detail field. Another option could be the `PositionUpdateException` exception

2024-05-15 08:38 UTC, josh-burton commented
> Hi @josh-burton,
> 
> Sorry for the delay and thank you for creating this PR. In general the changes look good, I have made a few small remarks which would be great if you can address those.

Thanks for the review. I believe I've addressed them now.

2024-05-15 11:43 UTC, mvanbeusekom commented
When merged solves #1513

2024-05-15 21:56 UTC, josh-burton commented on geolocator_web/lib/src/html_geolocation_manager.dart
> +      completer.completeError(e);
ok, my only concern there is the underlying exception will be lost. Perhaps we could add an optional cause field to the PositionUpdateException?

2024-05-15 22:04 UTC, josh-burton commented
@mvanbeusekom I see the workflows are failing. I had bumped the geolocator_web version to 4.0 as its a breaking change, but as 4.0 is not published the workflows now error.

What's the correct fix here?

2024-05-16 05:42 UTC, mvanbeusekom commented
The best would be to split the changes into 2 PRs. One updating the geolocator_web package and a second bumping the version for the geolocator package.

- However in this case the change in the geolocator package is so small that I don't mind the failing build. As long as the steps for the geolocator_web are green.

2024-05-16 06:49 UTC, mvanbeusekom approved these changes
LGTM

2024-05-16 06:49 UTC, merged