Wrapped all global functions in a private class and made them static.
Baseflow/flutter-geolocator pull request #529
Opened 2020-09-24 10:24 UTC by Sempakonka

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
This PR introduces a new way of calling the geolocation methods. A clearer way to keep your code distinct from the geolocation methods.

### :arrow_heading_down: What is the current behavior?
The current way of calling methods is by just typing the name of the desired method. This can cause confusion as some method names are quite often for a global use.

### :new: What is the new behavior (if this is a feature change)?
With the new way you call a method by first defining the plugin (geolocator) followed by the desired method.

### :boom: Does this PR introduce a breaking change?
No, it is not a breaking change. However all current (global) methods have been made obsolete.

### :bug: Recommendations for testing
N/A

### :memo: Links to relevant issues/docs
[524](https://github.com/Baseflow/flutter-geolocator/issues/524)

### :thinking: Checklist before submitting

- [X] All projects build
- [X] Follows style guide lines ([code style guide](https://github.com/BaseflowIT/flutter-geolocator/blob/develop/CONTRIBUTING.md))
- [X] Relevant documentation was updated
- [X] Rebased onto current develop

2020-09-27 14:00 UTC, mvanbeusekom requested changes
@Sempakonka the code change look good, I just have some suggestions to improve the documentation.

2020-10-01 10:42 UTC, mvanbeusekom approved these changes
LGTM

2020-10-01 23:21 UTC, jonasbeyer commented
Why has the Geolocator class been removed? I built my own wrapper class around the Gelocator instance provided via depency injection and I really liked that approach.

2020-10-08 09:37 UTC, mvanbeusekom approved these changes
LGTM!

2020-10-08 10:11 UTC, merged