Callback locationservice geolocator
Baseflow/flutter-geolocator pull request #742
Opened 2021-06-03 13:11 UTC by florissmit1

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Feature, docs updated and example app edited

### :arrow_heading_down: What is the current behavior?
At the moment it's not possible to track if the location service of the device is enabled/disabled 

### :new: What is the new behavior (if this is a feature change)?
By starting the serviceStatusStream, an event will be fired when the user turns on/off the devices location service in the settings or in the notification bar

### :boom: Does this PR introduce a breaking change?
No

### :bug: Recommendations for testing
Use the (new) example application

### :memo: Links to relevant issues/docs

### :thinking: Checklist before submitting

- [ ] I made sure all projects build.
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [ ] I updated the relevant documentation.
- [ ] I rebased onto current `master`.

2021-06-03 17:19 UTC, mvanbeusekom requested changes
Hi @florissmit1, 

Good start, I made some remarks in the Dart and Java implementation which in overal look good but can have some small improvements. 

Regarding the Objective-C implementation, I think we need to split the logic of the `FlutterStreamHandler` into two different classes (similar to the Java implementation). That means we need to create a separate `PositionStreamHandler` and a `LocationServiceStreamHandler` both implementing the `FlutterStreamHandler` class. This would solve the problem of the current `onListenWithArguments` method where two streams are mixed on different channels.

Now I can imagine that this sounds a bit daunting, so if you'd like I can help and move out the current stream handler implementation (which takes care of the position updates) into its own class so you have an example you can look at and copy for the location service update stream handler. Please let me know if this is something you would like and I will get started on it tomorrow morning.

In the meantime you can go through the other comments and make the necessary changes.

2021-06-03 17:19 UTC, mvanbeusekom commented on geolocator/example/lib/main.dart
> +enum _PositionItemType { permission, position, locationservicestatus }
Dart style guide suggests to use lower camel casing for enum values. Meaning the initial letter of a word is written in lower case, and initial letter of sub-sequent words are written with in upper case. Also add a comma after the last enum so formatting will put each element on its own line:
```suggestion
enum _PositionItemType { 
  permission,
  position,
  locationServiceStatus, 
}
```

2021-06-03 17:19 UTC, mvanbeusekom commented on geolocator/lib/geolocator.dart
> +
nit: redundant empty line which should be removed.
```suggestion
```

2021-06-03 17:19 UTC, mvanbeusekom commented on geolocator/ios/Classes/Utils/ServiceStatus.h
> +}
This interface definition can be removed.
```suggestion
```

2021-06-04 13:28 UTC, aytunch commented
Sorry if this is not related but is there a `locationservice` concept in iOS? I was using a separate package to get this stream and it was only for Android. 
So when this is merged will it work for both Android and iOS? 
Can't wait this to be merged to geolocator so we use one less package :)

2021-06-04 14:16 UTC, mvanbeusekom commented
> Sorry if this is not related but is there a `locationservice` concept in iOS? I was using a separate package to get this stream and it was only for Android.
> So when this is merged will it work for both Android and iOS?
> Can't wait this to be merged to geolocator so we use one less package :)

Hi @aytunch, yes this update will also work on iOS. We are close on finishing the feature, just a little more refactoring on the iOS side, so hang on just a little bit longer ;).

2021-06-10 14:58 UTC, mvanbeusekom requested changes
The code implementation looks good, but I left a whole bunch of comments regarding the code style which should be fixed.

2021-06-10 14:58 UTC, mvanbeusekom commented on geolocator/android/src/main/java/com/baseflow/geolocator/LocationServiceHandlerImpl.java
> +        activity.registerReceiver(this.receiver, filter);
Move this check to the top of the method. Now you are executing quite some code that is unnecessary when the `activity == null`.

Two other small nits:
1. We try to follow the Google Java Style guide which recommends always to uses braces for your `if` statement (see suggestion);
2. You can remove the redundant `this.` syntax (so the code is consistent with the other code in the project).

```suggestion
        if(activity == null) { 
            return;
        }
        
        IntentFilter filter = new IntentFilter(LocationManager.PROVIDERS_CHANGED_ACTION);
        filter.addAction(Intent.ACTION_PROVIDER_CHANGED);
       receiver = new LocationServiceStatusReceiver(events);
        activity.registerReceiver(receiver, filter);
```

2021-06-10 14:58 UTC, mvanbeusekom commented on geolocator/android/src/main/java/com/baseflow/geolocator/location/LocationServiceStatusReceiver.java
> +}
nit: it is considered to always end a file with a new line. In some cases this might lead to problems when using code automation tools not being able to parse the file correctly if the new line is missing. Although it probably won't cause any problems it is still good practice to add the line.

```suggestion
}

```

2021-06-10 14:58 UTC, mvanbeusekom commented on geolocator/ios/Classes/GeolocatorPlugin.m
> +
nit: remove redundant empty line:

```suggestion
```

2021-06-10 14:58 UTC, mvanbeusekom commented on geolocator/ios/Classes/GeolocatorPlugin.m
> +
nit: remove redundant empty line
```suggestion
```

2021-06-10 14:58 UTC, mvanbeusekom commented on geolocator/ios/Classes/Handlers/LocationServiceStreamHandler.h
> +
nit: remove redundant empty line

```suggestion
```

2021-06-10 14:58 UTC, mvanbeusekom commented on geolocator/ios/Classes/Handlers/LocationServiceStreamHandler.m
> +}
nit: remove redundant empty lines (code should be concise, see also [Objective-C code style](https://google.github.io/styleguide/objcguide.html) guidelines):
```suggestion
@implementation LocationServiceStreamHandler {
  FlutterEventSink _eventSink;
}
```

2021-06-10 14:58 UTC, mvanbeusekom commented on geolocator/ios/Classes/Handlers/LocationServiceStreamHandler.m
> +            }
nit: Correct the indentation and add spaces around the if:

```suggestion
    if (self.locationManager == nil) {
        self.locationManager = [[CLLocationManager alloc] init];
        self.locationManager.delegate = self;
    }
```

2021-06-10 14:58 UTC, mvanbeusekom commented on geolocator/ios/Classes/Handlers/LocationServiceStreamHandler.m
> +    if([CLLocationManager locationServicesEnabled]){
nit: add spaces around the `if` statement:

```suggestion
    if ([CLLocationManager locationServicesEnabled]) {
```

2021-06-11 13:58 UTC, mvanbeusekom approved these changes
LGTM

2021-06-11 13:58 UTC, merged

2021-06-11 14:26 UTC, mvanbeusekom commented
@aytunch we just released version 7.1.0 which contains the new `Geolocator.getServiceStatusStream()` method which will allow you to listen for updates regarding the location service.

Please let us know if you have any questions or encounter any problems.

2021-06-11 14:52 UTC, aytunch commented
@mvanbeusekom thanks for the mention. I am so glad `getServiceStatusStream` is now in `geolocator`. I will be replacing the stream I used from `location_permissions` in to `geolocator` and test my app. I will let you know if any problems occur.