Temporary precise location interface
Baseflow/flutter-geolocator pull request #763
Opened 2021-06-24 13:58 UTC by florissmit1

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Feature

### :arrow_heading_down: What is the current behavior?
Currently users can't request temporary full accuracy location fetching

### :new: What is the new behavior (if this is a feature change)?
Users can now request temporary full accuracy location fetching by using the 'requestTemporaryFullAccuracy'

### :boom: Does this PR introduce a breaking change?
No

### :bug: Recommendations for testing
Use the example application

### :memo: Links to relevant issues/docs
Does not apply

### :thinking: Checklist before submitting

- [ ] I made sure all projects build.
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [ ] I updated the relevant documentation.
- [ ] I rebased onto current `master`.

2021-06-25 10:11 UTC, ydag commented on geolocator/ios/Classes/Handlers/LocationAccuracyHandler.m
> +                                          message:@"The temporary accuracy dictionary key is not set in the infop.list"
info.plist :)

2021-06-25 10:13 UTC, ydag commented on geolocator_platform_interface/lib/src/geolocator_platform_interface.dart
> +  /// `Infop.list`.
Info.plist

2021-06-25 10:22 UTC, ydag commented on geolocator/ios/Classes/Handlers/LocationAccuracyHandler.m
> +- (void) requestTemporaryFullAccuracyWithResult:(FlutterResult)result {
Maybe it would be a nice thing to add `API_AVAILABLE(ios(14))` since this method will be used only iOS 14+.      

```
- (void) requestTemporaryFullAccuracyWithResult:(FlutterResult)result API_AVAILABLE(ios(14)) {
... 
}
```

2021-06-25 10:47 UTC, ydag commented on geolocator_platform_interface/lib/src/errors/approximate_location_not_supported_exception.dart
> +/// only thrown when using iOS 13 or below
```suggestion
/// only thrown when using iOS 13 or below.
```

2021-06-25 10:50 UTC, ydag commented on geolocator_platform_interface/lib/src/errors/approximate_location_not_supported_exception.dart
> +  /// Constructs the [ApproximateLocationNotSupportedException]
```suggestion
  /// Constructs the [ApproximateLocationNotSupportedException].
```

2021-06-25 10:50 UTC, ydag commented on geolocator_platform_interface/lib/src/errors/approximate_location_not_supported_exception.dart
> +  /// A [message] describing more details about the exception
```suggestion
  /// A [message] describing more details about the exception.
```

2021-06-25 10:50 UTC, ydag commented on geolocator_platform_interface/lib/src/errors/approximate_location_not_supported_exception.dart
> +          'or above.';
```suggestion
          ' or above.';
```

2021-06-25 10:51 UTC, ydag commented on geolocator_platform_interface/lib/src/errors/precise_accuracy_enabled_exception.dart
> +  /// Constructs the [PreciseAccuracyEnabledException]
```suggestion
  /// Constructs the [PreciseAccuracyEnabledException].
```

2021-06-25 10:53 UTC, ydag commented on geolocator_platform_interface/lib/src/geolocator_platform_interface.dart
> +  /// Location is not supported (iOS 13 or below)
```suggestion
  /// Location is not supported (iOS 13 or below).
```

2021-06-25 13:35 UTC, renefloor commented on geolocator_platform_interface/lib/src/errors/accuracy_dictionary_not_found_exception.dart
> +class AccuracyDictionaryNotFoundException implements Exception {
Is there any difference between this class and `permission_definitions_not_found_exception.dart`?
I understand what this exception is, but `AccuracyDictionaryNotFoundException` is a bit cryptic. Thinking of a different name I thought that you could just use `PermissionDefinitionsNotFoundException`.

2021-06-25 13:35 UTC, renefloor commented on geolocator_platform_interface/lib/src/errors/precise_accuracy_enabled_exception.dart
> +class PreciseAccuracyEnabledException implements Exception {
I don't know much about the location accuracy. However, I believe that with other permissions if you request a permission that is already granted you just get `granted`. Wouldn't you do a similar thing here?

2021-06-25 13:40 UTC, florissmit1 commented on geolocator_platform_interface/lib/src/errors/precise_accuracy_enabled_exception.dart
> +class PreciseAccuracyEnabledException implements Exception {
When requesting temporary precise location, the pop up wont show up if the user already gave permission. In this case, an `NSError` Will be returned, that's why I thought returning an exception is the correct way

2021-06-25 13:40 UTC, florissmit1 commented on geolocator_platform_interface/lib/src/errors/accuracy_dictionary_not_found_exception.dart
> +class AccuracyDictionaryNotFoundException implements Exception {
Sounds like a good plan! Thanks

2021-07-02 09:20 UTC, mvanbeusekom requested changes
Some changes regarding the documentation.

2021-07-02 09:20 UTC, mvanbeusekom commented on geolocator_platform_interface/lib/src/errors/approximate_location_not_supported_exception.dart
> +/// only thrown when using iOS 13 or below.
The documentation only mentions the use of iOS but what happens when you use another platform (Android or Web)?

I think in those cases we should throw the same exception (which is the responsibility of the `geolocator` package and should not be implemented here) but we should update the documentation here to mention other platforms (or make it clear that this exception is thrown on anything other than iOS 14).

2021-07-02 09:20 UTC, mvanbeusekom commented on geolocator_platform_interface/lib/src/geolocator_platform_interface.dart
> +  /// Throws a [AccuracyDictionaryNotFoundException] when the key
Should be update to:

```suggestion
  /// Throws a [PermissionDefinitionsNotFoundException] when the key
```

2021-07-02 09:20 UTC, mvanbeusekom commented on geolocator_platform_interface/lib/src/geolocator_platform_interface.dart
> +  /// Location is not supported (iOS 13 or below).
This should also include the other platforms (Android, Web, potential future platforms). Maybe something like:

```suggestion
  /// Throws a [ApproximateLocationNotSupportedException] when Approximate
  /// Location is not supported (iOS 13 or below and on other platforms).
```

2021-07-02 16:53 UTC, mvanbeusekom requested changes
One little mistake that should be corrected.

2021-07-02 16:53 UTC, mvanbeusekom commented on geolocator_platform_interface/lib/src/enums/location_accuracy.dart
> +  /// matches [LocationAccuracy.lowest] on devices using iOS 13 or below.
nit: we also support other platforms then iOS and Android so we should reflect this in our documentation. Maybe change this to:

```suggestion
  /// Location accuracy is reduced for iOS 14+ devices, matches the
  /// [LocationAccuracy.lowest] on iOS 13 and below and all other platforms.
```

2021-07-05 11:11 UTC, mvanbeusekom approved these changes
LGTM

2021-07-05 11:16 UTC, merged