Clarified docs getLocationAccuracy and added enum value for Android devices
Baseflow/flutter-geolocator pull request #769
Opened 2021-07-02 08:32 UTC by florissmit1

…or android to the LocationAccuracyStatus enum

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Docs update / small implementation change

### :arrow_heading_down: What is the current behavior?
Currently when Android users execute the `getLocationAccuracy()` method a PluginException will be thrown. Also, the code documentation did not mention about the iOS only support.

### :new: What is the new behavior (if this is a feature change)?
When Android users execute the `getLocationAccuracy()` method now, a LocationAccuracyStatus.unknown will be returned, since Android does not support Approximate location yet. Also the documentation has been clarified.

### :boom: Does this PR introduce a breaking change?
No

### :bug: Recommendations for testing
Does not apply

### :memo: Links to relevant issues/docs
Does not apply

### :thinking: Checklist before submitting

- [ ] I made sure all projects build.
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [ ] I updated the relevant documentation.
- [ ] I rebased onto current `master`.

2021-07-02 09:53 UTC, mvanbeusekom requested changes

2021-07-02 09:53 UTC, mvanbeusekom commented on geolocator_platform_interface/lib/src/implementations/method_channel_geolocator.dart
> +    }
This code should be part of the `geolocator` package and not the `geolocator_platform_interface`.  The `geolocator_platoform_interface` package should always be platform agnostic (as in it should not know anything about platforms or platform specific code).

Also the condition is not correct. It will now always return `LocationAccuracyStatus.unknown` when the platform IS iOS.

2021-07-02 09:53 UTC, mvanbeusekom commented on geolocator_platform_interface/CHANGELOG.md
> +- Documentation `getLocationAccuracy()` method clarified
Missing period:
```suggestion
- Documentation `getLocationAccuracy()` method clarified.
```

2021-07-02 09:53 UTC, mvanbeusekom commented on geolocator_platform_interface/CHANGELOG.md
> +- On Android devices, `getLocationAccuracy()` now returns a LocationAccuracyStatus.unknown value
The `geolocator_platform_interface` should be platform agnostic (not know about platform compatibility) and therefore we should not add the implementation to return a different state on Android in this package (see also later comment). This makes this release note incorrect maybe update it to something like this:  

```suggestion
- Extended the `LocationAccuracyStatus` enum with a `LocationAccuracyStatus.unknown` value, which can be used by platforms that don't support location accuracy features.
```

2021-07-02 09:53 UTC, mvanbeusekom commented on geolocator_platform_interface/lib/src/geolocator_platform_interface.dart
> +  /// [LocationAccuracyStatus.unknown] will be returned.
The geolocator also supports the `Web` platform and hopefully soon also others like Linux, MacOS, Windows and embedded systems. So this documentation is not correct maybe update it to:

 ```suggestion
  /// When executing the method on platforms that don't support location 
  /// accuracy features [LocationAccuracyStatus.unknown] should be returned.
```

2021-07-02 09:53 UTC, mvanbeusekom commented on geolocator_platform_interface/test/src/implementations/method_channel_geolocator_test.dart
> +      });
This unit-test can be removed as the unknown implementation should not be part of the `geolocator_platform_interface`.

2021-07-02 09:53 UTC, mvanbeusekom commented on geolocator_platform_interface/test/src/implementations/method_channel_geolocator_test.dart
> +      test('Should receive reduced accuracy if Location Accuracy is reduced',
This test has the same name as the the test on line 139 which is not allowed and should have a different name explaining the differences.

2021-07-05 11:41 UTC, mvanbeusekom requested changes
One small last change.

2021-07-05 11:41 UTC, mvanbeusekom commented on geolocator_platform_interface/lib/src/implementations/method_channel_geolocator.dart
> +import 'package:flutter/foundation.dart';
nit: I think this import has become obsolete and can be removed.
```suggestion
```

2021-07-05 11:56 UTC, mvanbeusekom approved these changes
LGTM

2021-07-05 11:56 UTC, merged

2021-08-10 19:38 UTC, helixbooks commented
Hi there! This is still broken for me on v7.4.0.

When running `getLocationAccuracy()` on an Android device, a `MissingPluginException` is still being thrown.