Restructured GitHub workflow and example app for web
Baseflow/flutter-geolocator pull request #779
Opened 2021-07-05 14:02 UTC by mvanbeusekom

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Maintenance

### :arrow_heading_down: What is the current behavior?

Currently CI is configured to run one job configured with different steps to test format, analyse, etc... This has the disadvantage that steps are run synchronously and also hides tasks from the GitHub overview (as developer you'll have to do extra navigation to see which step failed).

Additionally the `geolocator_web` package doesn't have a dedicated example App which makes debugging more difficult. And also doesn't allow the CI to compile the changes.

### :new: What is the new behavior (if this is a feature change)?

The new configuration creates different jobs for each task solving the above problems and also gives more options for future configuration.

This PR also adds a dedicated example App for the `geolocator_web` package.

### :boom: Does this PR introduce a breaking change?

No

### :bug: Recommendations for testing

### :memo: Links to relevant issues/docs

### :thinking: Checklist before submitting

- [x] I made sure all projects build.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [x] I updated the relevant documentation.
- [x] I rebased onto current `master`.

2021-07-05 14:32 UTC, renefloor requested changes

2021-07-05 14:32 UTC, renefloor commented on .github/workflows/app_facing_package.yaml
> +  # Job configuration for the Flutter State Challenge App
Multiple references to state challenge

2021-07-05 14:32 UTC, renefloor commented on .github/workflows/app_facing_package.yaml
> +    runs-on: ubuntu-latest
What's the benefit of Ubuntu?

2021-07-05 14:50 UTC, renefloor requested changes

2021-07-05 14:50 UTC, renefloor commented on geolocator_web/example/README.md
> +samples, guidance on mobile development, and a full API reference.
Would be nice to slightly update this

2021-07-05 14:50 UTC, renefloor commented on geolocator_web/example/lib/main.dart
> +              );
I would set this on 1 line.
```suggestion
              setState(() {});
```

2021-07-06 07:33 UTC, mvanbeusekom commented on .github/workflows/app_facing_package.yaml
> +    runs-on: ubuntu-latest
From a GitHub usage / license perspective there is no real benefit. GitHub runs their Windows and Ubuntu VMs in Azure (Standard DS2 v2 virtual machines). The macOS machines are part of GitHubs own macOS cloud solution. Personally I felt the Ubuntu configuration is more reliable but this is by no means backed by any proof. 

More information on GitHub Hosted runners can be found [here](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners).

From a technical perspective I think it is good to also make sure things work on different operating systems.

2021-07-06 10:23 UTC, mvanbeusekom commented on .github/workflows/app_facing_package.yaml
> +  # Job configuration for the Flutter State Challenge App
Fixed.

2021-07-06 10:23 UTC, mvanbeusekom commented on geolocator_web/example/README.md
> +samples, guidance on mobile development, and a full API reference.
Fixed.

2021-07-06 10:23 UTC, mvanbeusekom commented on geolocator_web/example/lib/main.dart
> +              );
Fixed.

2021-07-07 08:13 UTC, renefloor approved these changes
Some nits

2021-07-07 08:13 UTC, renefloor commented on geolocator_web/example/lib/main.dart
> +  static final String _kPermissionGrantedMessage = 'Permission granted.';
Why wouldn't you define these as const?

I believe using 'kName' is not a convention in dart. [At least constant are just 'name'.](https://dart.dev/guides/language/effective-dart/style#prefer-using-lowercamelcase-for-constant-names)

2021-07-07 08:13 UTC, renefloor commented on geolocator_web/example/lib/main.dart
> +    const sizedBox = SizedBox(
I would name this 'padding' or something like that.

2021-07-08 07:15 UTC, merged