Ios location options geolocator_apple package
Baseflow/flutter-geolocator pull request #802
Opened 2021-07-30 08:25 UTC by florissmit1

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Feature

### :arrow_heading_down: What is the current behavior?

### :new: What is the new behavior (if this is a feature change)?
Added the ActivityType enum/property and the pauseLocationUpdatesAutomatically property to the geolocator_apple package

### :boom: Does this PR introduce a breaking change?
No

### :bug: Recommendations for testing
Does not apply

### :memo: Links to relevant issues/docs
Does not apply

### :thinking: Checklist before submitting

- [ ] I made sure all projects build.
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [ ] I updated the relevant documentation.
- [ ] I rebased onto current `master`.

2021-07-30 10:37 UTC, mvanbeusekom requested changes
Would be nice if we make a barrel file which exports all public types, so consumers don't have to import a lot of different files:

`lib/geolocator_apple.dart` barrel file:

```dart
export 'src/types/activity_type.dart';
export 'src/types/apple_settings.dart';
```

This means you need to move the `activity_type.dart` and `apple_settings.dart` into the `lib/src/types` folder.

2021-07-30 10:37 UTC, mvanbeusekom commented on geolocator_apple/lib/ios_options.dart
> +class IosOptions extends LocationOptions {
I think we agreed to call this `AppleSettings` (not `IosOptions`). Also the base class should be the `LocationSettings` class (`LocationOptions` doesn't exist anymore in your new version of the `geoloator_platform_interface` package).

2021-07-30 10:53 UTC, florissmit1 commented on geolocator_apple/lib/ios_options.dart
> +class IosOptions extends LocationOptions {
You're right, my bad.

2021-07-30 15:29 UTC, mvanbeusekom requested changes

2021-07-30 15:29 UTC, mvanbeusekom commented on geolocator_apple/ios/Classes/Handlers/GeolocationHandler.m
> +    }
This statement can be simplified to (as it is already passed as a boolean):

```suggestion
    locationManager.pausesLocationUpdatesAutomatically = pauseLocationUpdatesAutomatically;

```

2021-07-30 15:29 UTC, mvanbeusekom commented on geolocator_apple/ios/Classes/GeolocatorPlugin.m
> +      NSNumber* pauseLocationUpdatesAutomatically = [NSNumber numberWithBool:(bool)arguments[@"pauseLocationUpdatesAutomatically"]];
We should try to parse data coming from Dart as early as possible and work with strong types in the rest of the code. In this case the `pauseLocationUpdatesAutomatically` parameter is supposed to be a boolean, however this is transported from Dart to Objective-C as `NSNumber` pointer (because theoretically it can be `null`, see also the [Flutter documentation](https://flutter.dev/docs/development/platform-integration/platform-channels#codec)). 

This means we need to convert it back to a boolean as soon as possible, and since we determined that a `null` value should be treated as `false` we can do that here. So first lets a reference to the `NSNumber` pointer:

```suggestion
      NSNumber* pauseLocationUpdatesAutomatically = arguments[@"pauseLocationUpdatesAutomatically"];
```

Notice that I removed the `(bool)` cast, this will give a problem if someone sends `nil`.

And when we pass it to the `startListeningWithDesiredAccuracy` method we convert it to a boolean (see next comment).

2021-07-30 15:29 UTC, mvanbeusekom commented on geolocator_apple/ios/Classes/GeolocatorPlugin.m
> +                        pauseLocationUpdatesAutomatically:pauseLocationUpdatesAutomatically
Don't pass a `NSNumber` pointer but the strongly type boolean value:
```suggestion
                        pauseLocationUpdatesAutomatically:pauseLocationUpdatesAutomatically && [pauseLocationUpdatesAutomatically boolValue]
```

2021-07-30 15:29 UTC, mvanbeusekom commented on geolocator_apple/ios/Classes/Handlers/GeolocationHandler.h
> +pauseLocationUpdatesAutomatically:(NSNumber* _Nullable)pauseLocationUpdatesAutomatically
Don't accept the `NSNumber` type here if we know we need a boolean (this will force calling code to deal with conversions):
```suggestion
pauseLocationUpdatesAutomatically:(BOOL)pauseLocationUpdatesAutomatically
```

2021-07-30 15:29 UTC, mvanbeusekom commented on geolocator_apple/ios/Classes/Handlers/PositionStreamHandler.m
> +      NSNumber* pauseLocationUpdatesAutomatically = [NSNumber numberWithBool:(bool)arguments[@"pauseLocationUpdatesAutomatically"]];
We should try to parse data coming from Dart as early as possible and work with strong types in the rest of the code. In this case the `pauseLocationUpdatesAutomatically` parameter is supposed to be a boolean, however this is transported from Dart to Objective-C as `NSNumber` pointer (because theoretically it can be `null`, see also the [Flutter documentation](https://flutter.dev/docs/development/platform-integration/platform-channels#codec)). 

This means we need to convert it back to a boolean as soon as possible, and since we determined that a `null` value should be treated as `false` we can do that here. So first lets a reference to the `NSNumber` pointer:

```suggestion
      NSNumber* pauseLocationUpdatesAutomatically = arguments[@"pauseLocationUpdatesAutomatically"];
```

Notice that I removed the `(bool)` cast, this will give a problem if someone sends `nil`.

And when we pass it to the `startListeningWithDesiredAccuracy` method we convert it to a boolean (see next comment).

2021-07-30 15:29 UTC, mvanbeusekom commented on geolocator_apple/ios/Classes/Handlers/PositionStreamHandler.m
> +                                     pauseLocationUpdatesAutomatically:pauseLocationUpdatesAutomatically
Don't pass a `NSNumber` pointer but the strongly type boolean value:
```suggestion
                        pauseLocationUpdatesAutomatically:pauseLocationUpdatesAutomatically && [pauseLocationUpdatesAutomatically boolValue]
```

2021-07-30 15:29 UTC, mvanbeusekom commented on geolocator_apple/lib/src/types/activity_type.dart
> +/// Represents the possible iOS activity types
nit: missing period.

```suggestion
/// Represents the possible iOS activity types.
```

2021-07-30 15:29 UTC, mvanbeusekom commented on geolocator_apple/lib/src/types/apple_settings.dart
> +  /// Initializes a new [IosSpecificSettings] instance with default values.
Use correct type in comments:

```suggestion
  /// Initializes a new [AppleSettings] instance with default values.
```

2021-07-30 15:29 UTC, mvanbeusekom commented on geolocator_apple/pubspec.yaml
> +  # TODO: Path reference should be removed
nit: It is very helpful for others to explain when the path reference should be removed, similar to the comment you added at the `publish_to` tag:

```suggestion
  # TODO: Path reference should be removed when the final version of the geolocator_platform_interface is published.
```

2021-07-30 15:33 UTC, mvanbeusekom commented
@florissmit1 also the `geolocator_apple / Format` step failed indicating the formatting of the Dart code is invalid.

2021-08-30 07:03 UTC, mvanbeusekom approved these changes
LGTM

2021-08-30 07:04 UTC, merged