Android location options added to the geolocator_android package
Baseflow/flutter-geolocator pull request #803
Opened 2021-07-30 08:35 UTC by florissmit1

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Feature

### :arrow_heading_down: What is the current behavior?

### :new: What is the new behavior (if this is a feature change)?
Added the Android location options to the `lib` directory in the geolocator_android package. Moved the `forceAndroidLocationManager` property to the Android Location options instance.

### :boom: Does this PR introduce a breaking change?
No

### :bug: Recommendations for testing
Does not apply

### :memo: Links to relevant issues/docs
Does not apply

### :thinking: Checklist before submitting

- [ ] I made sure all projects build.
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [ ] I updated the relevant documentation.
- [ ] I rebased onto current `master`.

2021-07-30 10:54 UTC, mvanbeusekom requested changes
Same as with the Apple version, it would be good to create a barrel file which exposes the new types so consumers only have to import one file.

2021-07-30 10:54 UTC, mvanbeusekom commented on geolocator_android/lib/android_options.dart
> +class AndroidOptions extends LocationOptions {
This should be `AndroidSettings` and extend the `LocationSettings` class from the geolocator_platform_interface package.

2021-08-05 09:11 UTC, mvanbeusekom requested changes

2021-08-05 09:11 UTC, mvanbeusekom commented on geolocator_android/lib/src/types/android_settings.dart
> +    Duration? intervalDuration,
Shouldn't this also include the `timeLimit` parameter?

2021-08-05 11:19 UTC, florissmit1 commented on geolocator_android/lib/src/types/android_settings.dart
> +    Duration? intervalDuration,
U're right!

2021-08-30 07:01 UTC, merged