PositionStreams are now canceled when Location Services are disabled
Baseflow/flutter-geolocator pull request #823
Opened 2021-08-27 13:02 UTC by florissmit1

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Example app update

### :arrow_heading_down: What is the current behavior?
Currently, when Location Services are disabled on the user's mobile device the PositionStream is canceled and cannot be continued.

### :new: What is the new behavior (if this is a feature change)?
By making use of the Location Service Stream you can prevent this problem. The example app now makes use of this.

### :boom: Does this PR introduce a breaking change?
No

### :bug: Recommendations for testing
Use the example application

### :memo: Links to relevant issues/docs
Does not apply

### :thinking: Checklist before submitting

- [ ] I made sure all projects build.
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [ ] I updated the relevant documentation.
- [ ] I rebased onto current `master`.

2021-08-30 06:59 UTC, mvanbeusekom requested changes
Have a question about changing the iOS deployment target and a small code suggestion.

2021-08-30 06:59 UTC, mvanbeusekom commented on geolocator/example/ios/Flutter/AppFrameworkInfo.plist
> +  <string>9.0</string>
Why this change? Doesn't seem to be necessary, maybe you can rollback the changes in this file (together with the changes in `project.pbxproj`)

2021-08-30 06:59 UTC, mvanbeusekom commented on geolocator/example/ios/Runner.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
Why is it necessary to move to deployment target 9.0?

2021-08-30 06:59 UTC, mvanbeusekom commented on geolocator/example/ios/Runner.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
Same

2021-08-30 06:59 UTC, mvanbeusekom commented on geolocator/example/ios/Runner.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
Same

2021-08-30 06:59 UTC, mvanbeusekom commented on geolocator/example/lib/main.dart
> +                      }
You can shorten this a bit by using:
```suggestion
                      positionStreamStarted = !positionStreamStarted;
```

2021-08-30 06:59 UTC, mvanbeusekom commented on geolocator_apple/example/ios/Flutter/AppFrameworkInfo.plist
> +  <string>9.0</string>
Same as before, why the need to update deployment target?

2021-08-30 06:59 UTC, mvanbeusekom commented on geolocator_apple/example/ios/Runner.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
Same

2021-08-30 06:59 UTC, mvanbeusekom commented on geolocator_apple/example/ios/Runner.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
Same

2021-08-30 06:59 UTC, mvanbeusekom commented on geolocator_apple/example/ios/Runner.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
Same

2021-09-03 06:33 UTC, florissmit1 commented on geolocator/example/lib/main.dart
> +                      }
Thanks, I thought it was 'cleaner' to make use of a if statement in this case.

2021-09-03 07:22 UTC, mvanbeusekom commented
@florissmit1 looks good, only needs to update the pubspec.yaml and changelog.md with a new version (patch).

2021-09-15 07:27 UTC, mvanbeusekom approved these changes
LGTM

2021-09-15 07:46 UTC, merged