fix. didChangeAppLifecycleState** goes into a loop when starting the …
Baseflow/flutter-geolocator pull request #834
Opened 2021-09-15 04:23 UTC by hoanglm4

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Bug fix.

### :arrow_heading_down: What is the current behavior?
**didChangeAppLifecycleState** goes into a loop after location request.
Version: 7.6.0
Config: **forceAndroidLocationManager**: false
Platform: Android only
Device Model: Xiaomi Only

### :new: What is the new behavior (if this is a feature change)?
**didChangeAppLifecycleState** not loop after location request.

### :boom: Does this PR introduce a breaking change?
None

### :bug: Recommendations for testing
None

### :memo: Links to relevant issues/docs
https://github.com/Baseflow/flutter-geolocator/issues/816

### :thinking: Checklist before submitting

- [x] I made sure all projects build.
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [ ] I updated the relevant documentation.
- [x] I rebased onto current `master`.

2021-09-15 07:10 UTC, mvanbeusekom requested changes
Hi @hoanglm4, thank you for this pull-request. I have been looking a long time on how to fix this issue and all becomes clear now. 

I do have some feedback on how to improve on your proposed solution, I hope you could send an update. Also please update the version number of the `./geolocator_android/pubspec.yaml` file and add an entry in the `./geolocator_android/CHANGELOG.md` file with a short description of the fix you made. This will allow us to more easily publish the changes.

2021-09-15 07:10 UTC, mvanbeusekom commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/location/FusedLocationClient.java
> +
We could extract this logic into a separate method and call it directly from the `onActivityResult` callback. That would take out this `if` statement and makes the code easier to understand. It will also reduce code duplication. I was thinking something like:

```java
private void requestPositionUpdates(LocationOptions locationOptions) {
    LocationRequest locationRequest = buildLocationRequest(locationOptions);
    fusedLocationProviderClient.requestLocationUpdates(
            locationRequest, locationCallback, Looper.getMainLooper());
}
```

Next we call this method on all locations where we currently call the `fusedLocationProviderClient.requestLocationUpdates()` method and in the `onActivityResult()` method where we currently call the `startPositionUpdates` method. This would remove the need for the `forceRequest` boolean and the additional if statement.

2021-09-19 03:34 UTC, hoanglm4 commented
Hi @mvanbeusekom ,
Sorry too late. Could u please help me review again.

Thanks

2021-09-19 07:42 UTC, mvanbeusekom approved these changes
LGTM, thank you for the bug fix. I really appreciate it.

2021-09-19 07:42 UTC, merged