Avoid usage of unofficial API
Baseflow/flutter-geolocator pull request #913
Opened 2021-12-07 16:39 UTC by maxammann

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

This PR removes the usage `com.google.android.gms.common.util.Strings;`. I'm trying to publish an app to F-Droid. Therefore, I'm stripping away the GMS dependency before packaging the final result. This actually works very well if I'm forcing the usage of the legacy location manager.

The only issue with my approach is that geolocator is using the Strings API which in fact is not even listed here: https://developers.google.com/android/reference/com/google/android/gms/common/package-summary

### :new: What is the new behavior (if this is a feature change)?

The new check is done using plain Java.

### :boom: Does this PR introduce a breaking change?

No.

### :bug: Recommendations for testing

None

### :memo: Links to relevant issues/docs

None

### :thinking: Checklist before submitting

- [x] I made sure all projects build.
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [x] I updated the relevant documentation.
- [x] I rebased onto current `master`.

2021-12-07 17:03 UTC, maxammann commented
This is related to [#fdroid](https://github.com/digitalfabrik/ehrenamtskarte/pull/427)

2021-12-13 10:50 UTC, maxammann commented
@mvanbeusekom I updated the changelog and the version. Is there anything left to do from my side?

2021-12-13 11:23 UTC, mvanbeusekom requested changes
Hi @maxammann,

Apologies, things have been a bit hectic and I missed your update. I have just one small issue with the version number. If you could fix that, I will make sure things are merged and published.

2021-12-13 11:23 UTC, mvanbeusekom commented on geolocator_android/CHANGELOG.md
> +## 3.0.0+5
Let's make this an official patch and use version 3.0.1
```suggestion
## 3.0.1
```

2021-12-13 11:23 UTC, mvanbeusekom commented on geolocator_android/pubspec.yaml
> +version: 3.0.0+5
Use the patch version here aswel:
```suggestion
version: 3.0.1
```

2021-12-13 11:47 UTC, maxammann commented
Done: I also created a PR about a bug: https://github.com/Baseflow/flutter-geolocator/pull/918/files

2021-12-13 11:51 UTC, mvanbeusekom approved these changes
LGTM

2021-12-13 11:51 UTC, merged