Export `ActivityType` at `geolocator.dart`
Baseflow/flutter-geolocator pull request #933
Opened 2022-01-06 02:50 UTC by mduccc

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
enhancement

### :arrow_heading_down: What is the current behavior?
When I use `AppleSettings` with `activityType` property, must import: 
`import 'package:geolocator_apple/geolocator_apple.dart';`

### :new: What is the new behavior (if this is a feature change)?
Export `ActivityType` at `geolocator.dart`.

Then all need to do:
`import 'package:geolocator/geolocator.dart';`

### :boom: Does this PR introduce a breaking change?

### :bug: Recommendations for testing

### :memo: Links to relevant issues/docs

### :thinking: Checklist before submitting

- [x] I made sure all projects build.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [x] I updated the relevant documentation.
- [x] I rebased onto current `master`.

2022-01-22 10:03 UTC, mvanbeusekom requested changes
Thank you for this submission and apologies for the late reply. I left one remark and would gladly merge your PR if you could provide a fix.

2022-01-22 10:03 UTC, mvanbeusekom commented on geolocator/lib/geolocator.dart
> +export 'package:geolocator_apple/geolocator_apple.dart';
The `ActivityType` should indeed be exported. However it would be better to add it to the `show` condition. 

We are in the progress of adding more logic to the `geolocator_apple` package and we don't want to expose everything by default through the `geolocator` app-facing package.

```suggestion
export 'package:geolocator_apple/geolocator_apple.dart' 
         show AppleSettings, ActivityType;
```

2022-01-24 09:05 UTC, mduccc commented on geolocator/lib/geolocator.dart
> +export 'package:geolocator_apple/geolocator_apple.dart';
> 

Yes. I fixed it!

2022-01-24 14:19 UTC, mvanbeusekom approved these changes
LGTM, thank you very much for this contribution.

2022-01-24 14:20 UTC, merged