Initial Windows support.
Baseflow/flutter-geolocator pull request #954
Opened 2022-01-21 17:36 UTC by azchohfi

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Feature

### :arrow_heading_down: What is the current behavior?
No Windows support 😭 

### :new: What is the new behavior (if this is a feature change)?
Support Windows 😄 

### :boom: Does this PR introduce a breaking change?
No

### :bug: Recommendations for testing
Test the example app building for Windows.

### :memo: Links to relevant issues/docs
#840 

### :thinking: Checklist before submitting

- [X] I made sure all projects build.
- [X] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [ ] I updated the relevant documentation.
- [X] I rebased onto current `master`.

2022-01-21 17:54 UTC, azchohfi commented
I just realized that the Windows version is not being built by the yaml files. Fixing that.

2022-01-21 19:11 UTC, azchohfi commented
Also, the geolocator_windows plugin is not ublished yet, so all these tasks will fail. Any idea how to proceed here?

2022-01-22 10:21 UTC, mvanbeusekom requested changes
Hi @azchohfi, 

Thank you for this PR, I really appreciate it. Personally I was also working on adding Windows support and took a bit different approach regarding the implementation. However I feel your PR will serve as a really good starting point for further development and we could release your implementation of the `geolocator_windows` package as a pre-release version if that is ok with you.

To solve you question:

> Also, the geolocator_windows plugin is not ublished yet, so all these tasks will fail. Any idea how to proceed here?

The best approach would be to create a PR containing only the `geolocator_windows` implementation and not update the `geolocator` package yet. This will allow us to merge and publish the `geolocator_windows` package and offer developers the option to start using it without advertising it in the `geolocator` app-facing package as of yet. This will also give us a change to iron out bugs and optimize the implementation.  So it would be great if you could undo all changes that were made to files in the `geolocator` package.

I have left some initial remarks regarding the version number.

2022-01-22 10:21 UTC, mvanbeusekom commented on geolocator_windows/pubspec.yaml
> +version: 1.0.0
Please update this version to `0.1.0` which will indicate this is a pre-release version of the plugin which is still under development:
```suggestion
version: 0.1.0
```

2022-01-22 10:21 UTC, mvanbeusekom commented on geolocator_windows/CHANGELOG.md
> +- Initial release.
Update version number here as well and maybe update the description to:

```suggestion
## 0.1.0

- Adds an initial implementation of Windows support for the geolocator plugin.
```

2022-01-24 15:20 UTC, mvanbeusekom requested changes
Hi @azchohfi, 

Thank you very much for your updates. The code is looking very good, I just have some small remarks regarding some of the dependencies in the pubspec.yaml. Would you mind to have a look at it?

2022-01-24 15:20 UTC, mvanbeusekom commented on geolocator_windows/pubspec.yaml
> +  flutter: ">=1.20.0"
As we are in the progress updating the requirements of the other packages at the moment we might as well use latest settings here:

```suggestion
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"
```

2022-01-24 15:20 UTC, mvanbeusekom commented on geolocator_windows/pubspec.yaml
> +  plugin_platform_interface: ^2.0.0
Lets make sure these are also updated to the latest versions (especially the `plugin_platform_interface` package contains an important bug fix):
```suggestion
  mockito: ^5.0.17
  plugin_platform_interface: ^2.1.2
```

2022-01-24 15:20 UTC, mvanbeusekom commented on geolocator_windows/example/pubspec.yaml
> +  sdk: ">=2.12.0 <3.0.0"
As we are in the progress updating the requirements of the other packages at the moment we might as well use latest settings here:

```suggestion
  sdk: ">=2.15.0 <3.0.0"
```

2022-01-24 15:20 UTC, mvanbeusekom commented on geolocator_windows/example/pubspec.yaml
> +  url_launcher: ^6.0.0-nullsafety.1
Let's make sure to update this dependency to the current stable version:
```suggestion
  url_launcher: ^6.0.18
```

2022-01-24 16:55 UTC, mvanbeusekom commented
Thank you for the updates @azchohfi. 

I have been trying to run the example application on my freshly setup Windows machine and I am running into some troubles. Maybe you could help me out with the following questions:

1. The first problem I ran into was CMake trying to run the `nuget install Microsoft.Windows.CppWinRT` and couldn't find the NuGet executable. Of course I solved this by downloading NuGet and adding it to the `Path` environment variable. However I was wondering if it wouldn't be better to add the nuget binary to the repo and use a relative path reference? I am not very familiar with Windows C++ development and I am not sure if this would be good or bad practice, maybe you can advise?
2. After making sure NuGet was available and running `flutter run` I stumbled on the following build error:
```
Launching lib\main.dart on Windows in debug mode...
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: The command "setlocal [C:\Users\mvanb\Projects\Flutter\geolocator\geolocator_windows\example\build\windows\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake [C:\Users\mvanb\Projects\Flutter\geolocator\geolocator_windows\example\build\windows\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [C:\Users\mvanb\Projects\Flutter\geolocator\geolocator_windows\example\build\windows\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: :cmEnd [C:\Users\mvanb\Projects\Flutter\geolocator\geolocator_windows\example\build\windows\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [C:\Users\mvanb\Projects\Flutter\geolocator\geolocator_windows\example\build\windows\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: :cmErrorLevel [C:\Users\mvanb\Projects\Flutter\geolocator\geolocator_windows\example\build\windows\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: exit /b %1 [C:\Users\mvanb\Projects\Flutter\geolocator\geolocator_windows\example\build\windows\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: :cmDone [C:\Users\mvanb\Projects\Flutter\geolocator\geolocator_windows\example\build\windows\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [C:\Users\mvanb\Projects\Flutter\geolocator\geolocator_windows\example\build\windows\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: :VCEnd" exited with code 1. [C:\Users\mvanb\Projects\Flutter\geolocator\geolocator_windows\example\build\windows\INSTALL.vcxproj]
Building Windows application...
Exception: Build process failed.
```

Here is the output of `flutter doctor -v`:
```
[✓] Flutter (Channel beta, 2.10.0-0.2.pre, on Microsoft Windows [Version 10.0.22000.434], locale en-NL)
    • Flutter version 2.10.0-0.2.pre at C:\Users\mvanb\development\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 73adb1406a (5 days ago), 2022-01-19 17:02:56 -0600
    • Engine revision 74b74b10ea
    • Dart version 2.16.0 (build 2.16.0-134.1.beta)
    • DevTools version 2.9.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32112.339
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.63.2)
    • VS Code at C:\Users\mvanb\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.434]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 97.0.1072.62

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

Do you have any idea what would be causing this error and how I could resolve it? I noticed everything builds fine on GitHub given the workflow you provided so I assume it is related to my setup.

2022-01-24 17:19 UTC, azchohfi commented
Sure, I can try to help!
1) Nuget files shouldn't be added to the git repo at all. They should be restored, just like any other Flutter package from Pub.Dev. The concept is exactly the same. There is already a cmake command to add nuget packages to projects, but it doesn't work with C++ just yet... only C#, so I don't see an easy way to make this not require nuget.exe in the path... I'm open for sugestions.
2) Not exactly sure what is happening with your env. Did you install the C++ workload for Desktop? I'm also using VS2022 (as opposed to 2019 that is installed on the CI) but both should work with the correct workloads installed. Can you try running "flutter run -d windows -v"? Maybe there is more info there.

2022-01-24 17:28 UTC, azchohfi commented
The Windows requirements are here:
https://docs.flutter.dev/get-started/install/windows#additional-windows-requirements
They mention that 2019 is required for flutter 2.8.x, but I'm using 2022 and it works fine.

2022-01-24 17:32 UTC, mvanbeusekom commented
Thanks you much appreciated. 

>Nuget files shouldn't be added to the git repo at all. They should be restored, just like any other Flutter package from Pub.Dev. The concept is exactly the same. There is already a cmake command to add nuget packages to projects, but it doesn't work with C++ just yet... only C#, so I don't see an easy way to make this not require nuget.exe in the path... I'm open for sugestions.

Sorry maybe I didn't explain it correctly, I didn't mean including the `Microsoft.Windows.CppWinRT` package as part of the repo but rather the `nuget.exe` CLI. I have noticed other OSS applications also do this systems or CI environments that don't have the NuGet CLI pre-installed or not available through the path environment variable. Instead we could include it as part of the repo, say in the `geolocator_windows\bin\nuget\nuget.exe`.

> Not exactly sure what is happening with your env. Did you install the C++ workload for Desktop? I'm also using VS2022 (as opposed to 2019 that is installed on the CI) but both should work with the correct workloads installed. Can you try running "flutter run -d windows -v"? Maybe there is more info there.

I have the default configuration of the "Desktop development with C++" Visual Studio Workload installed as documented on the Flutter requirements page. Below is the full log from `flutter run -d windows -v` command, would be great if you notice something that is missing of off: 
<details>
<summary> `flutter run -d windows -v` logs </summary>

```
[  +90 ms] executing: [C:\Users\mvanb\development\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +521 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 73adb1406a9cff796e2203ad16fd285220a6ec97
[        ] executing: [C:\Users\mvanb\development\flutter/] git tag --points-at 73adb1406a9cff796e2203ad16fd285220a6ec97
[  +54 ms] Exit code 0 from: git tag --points-at 73adb1406a9cff796e2203ad16fd285220a6ec97
[        ] 2.10.0-0.2.pre
[  +16 ms] executing: [C:\Users\mvanb\development\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +42 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] executing: [C:\Users\mvanb\development\flutter/] git ls-remote --get-url origin
[  +38 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +248 ms] Unable to locate an Android SDK.
[   +8 ms] executing: [C:\Users\mvanb\development\flutter/] git rev-parse --abbrev-ref HEAD
[  +38 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +75 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +78 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +116 ms] Skipping pub get: version match.
[  +47 ms] Found plugin url_launcher at
C:\Users\mvanb\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher-6.0.18\
[   +8 ms] Found plugin url_launcher_android at
C:\Users\mvanb\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_android-6.0.14\
[   +3 ms] Found plugin url_launcher_ios at
C:\Users\mvanb\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_ios-6.0.14\
[   +2 ms] Found plugin url_launcher_linux at
C:\Users\mvanb\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.3\
[   +2 ms] Found plugin url_launcher_macos at
C:\Users\mvanb\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.3\
[   +3 ms] Found plugin url_launcher_web at
C:\Users\mvanb\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-2.0.6\
[   +2 ms] Found plugin url_launcher_windows at
C:\Users\mvanb\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.2\
[   +5 ms] Found plugin geolocator_windows at C:\Users\mvanb\Projects\Flutter\geolocator\geolocator_windows\
[  +66 ms] Found plugin url_launcher at
C:\Users\mvanb\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher-6.0.18\
[   +1 ms] Found plugin url_launcher_android at
C:\Users\mvanb\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_android-6.0.14\
[   +1 ms] Found plugin url_launcher_ios at
C:\Users\mvanb\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_ios-6.0.14\
[   +1 ms] Found plugin url_launcher_linux at
C:\Users\mvanb\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.3\
[   +2 ms] Found plugin url_launcher_macos at
C:\Users\mvanb\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.3\
[   +3 ms] Found plugin url_launcher_web at
C:\Users\mvanb\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-2.0.6\
[   +1 ms] Found plugin url_launcher_windows at
C:\Users\mvanb\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.2\
[   +3 ms] Found plugin geolocator_windows at C:\Users\mvanb\Projects\Flutter\geolocator\geolocator_windows\
[ +138 ms] Initializing file store
[  +15 ms] Skipping target: gen_localizations
[   +6 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have
updated contents:
C:\Users\mvanb\Projects\Flutter\geolocator\geolocator_windows\example\.dart_tool\package_config_subset}
[  +25 ms] Found plugin url_launcher at
C:\Users\mvanb\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher-6.0.18\
[   +1 ms] Found plugin url_launcher_android at
C:\Users\mvanb\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_android-6.0.14\
[   +1 ms] Found plugin url_launcher_ios at
C:\Users\mvanb\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_ios-6.0.14\
[   +1 ms] Found plugin url_launcher_linux at
C:\Users\mvanb\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.3\
[   +1 ms] Found plugin url_launcher_macos at
C:\Users\mvanb\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.3\
[   +1 ms] Found plugin url_launcher_web at
C:\Users\mvanb\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-2.0.6\
[   +1 ms] Foun [...]

2022-01-24 18:03 UTC, azchohfi commented
1) We could do that, but it will increase the repository size with something that be easily downloaded (https://dist.nuget.org/win-x86-commandline/latest/nuget.exe). We could test the path, and if it doesn't have nuget.exe, then we download it and add it? That would probably work. I'll work on this.
2) The error seems to be a missing permission, but it feels wrong. Similar to https://github.com/flutter/flutter/issues/59890. Maybe a flutter clean can help? If not, try running the cmd elevated. Maybe if that doesn't work, you can you try running it from VS. There should be a generated sln file here: ```flutter-geolocator\geolocator_windows\example\build\windows\example.sln```. Maybe the logs there are more detailed.

2022-01-24 18:57 UTC, mvanbeusekom commented
> 1. We could do that, but it will increase the repository size with something that be easily downloaded (https://dist.nuget.org/win-x86-commandline/latest/nuget.exe). We could test the path, and if it doesn't have nuget.exe, then we download it and add it? That would probably work. I'll work on this.

That sounds like a great solution, looking forward to your update.

> 2. The error seems to be a missing permission, but it feels wrong. Similar to [Build error in flutter linux flutter/flutter#59890](https://github.com/flutter/flutter/issues/59890). Maybe a flutter clean can help? If not, try running the cmd elevated. Maybe if that doesn't work, you can you try running it from VS. There should be a generated sln file here: `flutter-geolocator\geolocator_windows\example\build\windows\example.sln`. Maybe the logs there are more detailed.

Running `flutter clean` indeed did the trick and the windows example app is running like a charm now, thanks!

2022-01-24 19:12 UTC, azchohfi commented
Ok, just finished this. Took me a while to get it right since it is heavily cached, and I thought I had it wrong. This should do the trick, but if you want to test it, just make sure to run flutter clean before each try (with/without nuget.exe on the path).

2022-01-24 19:42 UTC, mvanbeusekom approved these changes
> Ok, just finished this. Took me a while to get it right since it is heavily cached, and I thought I had it wrong. This should do the trick, but if you want to test it, just make sure to run flutter clean before each try (with/without nuget.exe on the path).

I have tried several scenarios and all seem to work perfectly. Thank you very much for the time and effort you put into this and helping me understand the environment. 

I will merge this PR now and publish the package. People who would like to include support for Windows can simply add an extra dependency to this package until we officially endorse it.

2022-01-24 19:42 UTC, merged

2022-01-24 19:44 UTC, azchohfi commented
Awesome!

2022-01-24 19:55 UTC, mvanbeusekom commented
Great stuff, merged and published. Is it ok if I send out a tweet mentioning you and your awesome contribution?

2022-01-24 20:01 UTC, azchohfi commented
Sure, not a problem at all!