Adds Android foreground location support
Baseflow/flutter-geolocator pull request #978
Opened 2022-02-11 17:38 UTC by Wackymax

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Feature: Adds support for background (Foreground service) support to Android for when the applications goes into the background while location stream is active

Related to PR: https://github.com/Baseflow/flutter-geolocator/pull/957

### :arrow_heading_down: What is the current behavior?

Currently when the application goes into background and the OS kills the activity then location streaming stops.

### :new: What is the new behavior (if this is a feature change)?

New options have been introduced on Android that will allow the users to configure the background behaviour allow the service to continue running in the background keeping the activity alive while the location stream is active.

### :boom: Does this PR introduce a breaking change?

A new Android service is introduced which changes the behaviour of the location stream to use the new service but existing apps will not know about this change.

### :bug: Recommendations for testing

Testing the normal mode to validate the location stream is still working as expected and testing the background mode with the application running in the background.

### :memo: Links to relevant issues/docs

https://github.com/Baseflow/flutter-geolocator/issues/948
https://github.com/Baseflow/flutter-geolocator/issues/53

### :thinking: Checklist before submitting

- [X] I made sure all projects build.
- [X] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [X] I updated the relevant documentation.
- [X] I rebased onto current `master`.

2022-02-12 10:16 UTC, mvanbeusekom commented on geolocator_android/CHANGELOG.md
> +- Added an Android service to retrieve location updates. This allows us to make the service a foreground service which will stay alive and continue processing location updates if if the application i
Nit: We should convert this into one bullet point as the current bullet points describe the implementation and release notes normally don't list implementation detail. I think we could convert this into something like:

```suggestion
- Adds support to make a foreground service and continue processing location updates when the application is moved into the background.
```

2022-02-12 10:16 UTC, mvanbeusekom commented on geolocator_android/CHANGELOG.md
> -
Nit: Please make sure all files end with an empty line. This is to ensure (older) POSIX

2022-02-12 11:22 UTC, mvanbeusekom requested changes
Thank you for splitting up the initial PR. I have reviewed these changes and the code overall looks very good. I just left some small remarks and some style change request. 

I would really appreciate it if you could go through these and provide an update.

2022-02-12 11:22 UTC, mvanbeusekom commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/MethodCallHandlerImpl.java
> +    void setBackgroundLocationService(@Nullable GeolocatorLocationService backgroundLocationService) {
Rename this too `setForegroundLocationService` and the parameter too `foregroundLocationService` to remove confusion with the Android Background service feature.

2022-02-12 11:22 UTC, mvanbeusekom commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/StreamHandlerImpl.java
> +    public void setBackgroundLocationService(@Nullable GeolocatorLocationService backgroundLocationService) {
Same, rename this to `setForegroundLocationService` and the parameter to `foregroundLocationService`.

2022-02-12 11:22 UTC, mvanbeusekom commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/StreamHandlerImpl.java
> +    @Nullable private GeolocatorLocationService backgroundLocationService;
Alignment and rename to `foregroundLocationService`.

2022-02-12 11:22 UTC, mvanbeusekom commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/location/AndroidIconResource.java
> +}
Nit: Add missing empty line.

2022-02-12 11:22 UTC, mvanbeusekom commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/location/BackgroundNotification.java
> +}
Nit: add missing empty line.

2022-02-12 11:22 UTC, mvanbeusekom commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/location/BackgroundNotification.java
> +            if (Build.VERSION.SDK_INT > 23) {
Use `Build.VERSION_CODES.M` instead to the `23` number literal:

```suggestion
            if (Build.VERSION.SDK_INT > Build.VERSION_CODES.M) {
```

2022-02-12 11:22 UTC, mvanbeusekom commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/location/ForegroundNotificationOptions.java
> +    private final boolean enableWakeLock;
Please decorate with attributes to indicate nullability.

2022-02-12 11:22 UTC, mvanbeusekom commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/location/ForegroundNotificationOptions.java
> +
Nit: remove redundant empty line.

2022-02-12 11:22 UTC, mvanbeusekom commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/location/NotificationImportance.java
> +}
Nit: add missing empty line.

2022-02-12 11:22 UTC, mvanbeusekom commented on geolocator_android/lib/geolocator_android.dart
> +export 'src/types/foreground_settings.dart' show ForegroundNotificationConfig;
Nit: add missing empty line.

2022-02-12 11:22 UTC, mvanbeusekom commented on geolocator_android/lib/src/types/android_settings.dart
>  }
Nit: since you are modifying this file, it would be great if you could also add an empty line here.

2022-02-12 11:22 UTC, mvanbeusekom commented on geolocator_android/lib/src/types/android_settings.dart
> +  /// showing the user that the service will continue running in the background
Nit: sentence should end with a period.
```suggestion
  /// showing the user that the service will continue running in the background.
```

2022-02-12 11:22 UTC, mvanbeusekom commented on geolocator_android/lib/src/types/foreground_settings.dart
> +/// Uniquely identifies an Android resource
Nit: sentence should end with a period.
```suggestion
/// Uniquely identifies an Android resource.
```

2022-02-12 11:22 UTC, mvanbeusekom commented on geolocator_android/lib/src/types/foreground_settings.dart
> +  /// Uniquely identifies an Android resource
Nit: sentence should end with a period.
```suggestion
  /// Uniquely identifies an Android resource.
```

2022-02-12 11:22 UTC, mvanbeusekom commented on geolocator_android/lib/src/types/foreground_settings.dart
> +  /// Returns a json representation of this class
Nit: sentence should end with a period and JSON should be all capitals.
```suggestion
  /// Returns a JSON representation of this class.
```

2022-02-12 11:22 UTC, mvanbeusekom commented on geolocator_android/lib/src/types/foreground_settings.dart
> +  /// Wifilock permissions should be obtained first by using a permissions library
Nit: sentence should end with a period.
```suggestion
  /// Wifi lock permissions should be obtained first by using a permissions library.
```

2022-02-12 11:22 UTC, mvanbeusekom commented on geolocator_android/lib/src/types/foreground_settings.dart
> +  /// Wakelock permissions should be obtained first by using a permissions library
Nit: sentence should end with a period.

```suggestion
  /// Wake lock permissions should be obtained first by using a permissions library.
```

2022-02-12 11:22 UTC, mvanbeusekom commented on geolocator_android/lib/src/types/foreground_settings.dart
> +  /// Returns a json representation of this class
Nit: sentence should end with a period and JSON should be all capitals.
```suggestion
  /// Returns a JSON representation of this class.
```

2022-02-12 11:22 UTC, mvanbeusekom commented on geolocator_android/pubspec.yaml
> +  geolocator_platform_interface: ^4.0.0+1
Version `4.0.0+1` doesn't exists, please update to `4.0.3`.
```suggestion
  geolocator_platform_interface: ^4.0.3
```

2022-02-12 12:18 UTC, Wackymax commented on geolocator_android/android/build.gradle
>  }
For some reason I already have an empty line on my side

2022-02-12 12:32 UTC, mvanbeusekom commented on geolocator_android/android/build.gradle
>  }
You are absolutely right, apologies. GitHub doesn't show it indeed. Only when it is missing GitHub will show an extra warning. Please ignore my requests about this.

2022-02-12 20:15 UTC, Wackymax commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/GeolocatorLocationService.java
> +        if (this.locationClient != null && geolocationManager != null) {
There is a lot of code form the library that is using "this" in some places. I've made updates to remove as far as possible.

2022-02-12 20:18 UTC, Wackymax commented on geolocator_android/android/src/main/AndroidManifest.xml
>  </manifest>
Once again, I see a empty line on my side. Not sure where in the process it gets removed

2022-02-12 20:19 UTC, Wackymax commented
I've applied the PR suggestions that were made

2022-02-12 20:27 UTC, Wackymax commented on geolocator_android/android/src/main/java/com/baseflow/geolocator/location/BackgroundNotification.java
> +    private NotificationCompat.Builder builder;
None of these can be null. Options wasn't being used so I removed it.

2022-02-13 08:50 UTC, mvanbeusekom reviewed
@Wackymax thanks for applying the requested changes. 

Having another look at the code I noticed the example App doesn't contain any changes. I am not to familiar with foreground services so I am not to sure if it is required to do any changes to make use of the background services.

However there is a new `ForegroundNotificationConfig` class as part of the Dart code, I think it would be good to reflect its usage in the example App. Would you mind giving this an update?

P.S. sorry for not realizing this in the first round. Really appreciate your efforts.

2022-02-13 14:48 UTC, mvanbeusekom approved these changes
LGTM, if you can fix the formatting and the Dart doc for the `enableWakeLock` field (see additional comment).

2022-02-13 14:48 UTC, mvanbeusekom commented on geolocator_android/lib/src/types/foreground_settings.dart
>    /// Wake lock permissions should be obtained first by using a permissions library.
According to the [Dart doc specifications](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#dartdoc-specific-requirements) the first paragraph should be a short self contained sentence followed by more elaborate paragraphs. Also lines should be wrapped at 80 characters according to the Dart style-guide.

Lets restructure this a little bit to for example:
```
  /// When enabled, a Wakelock is acquired when background execution is 
  /// started.
  ///
  /// If this is false then the system can still sleep and all location 
  /// events will be received at once when the system wakes up again.
  ///
  /// Wake lock permissions should be obtained first by using a permissions library.
```

2022-02-13 18:00 UTC, Wackymax commented on geolocator_android/lib/src/types/foreground_settings.dart
>    /// Wake lock permissions should be obtained first by using a permissions library.
Done. Sorry for all the back and forth. This is my first contribution to an open source project 😅

2022-02-13 18:07 UTC, merged

2022-02-13 18:21 UTC, mvanbeusekom commented
Thank you for all your effort @Wackymax. The geolocator_android package has just been published, this means it is now also possible to update #980 with the new reference. It would also be good to update the example App here.

2022-02-13 18:52 UTC, Wackymax commented
Thank you @mvanbeusekom,

I've updated [980](https://github.com/Baseflow/flutter-geolocator/pull/980). The example app does not set any settings at all so it didn't feel right updating it with Android settings. But I added the example to the readme docs.