Add foreground service location support
Baseflow/flutter-geolocator pull request #980
Opened 2022-02-11 17:47 UTC by Wackymax

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Feature: Adds support for background (Foreground service) support to Android for when the applications goes into the background while location stream is active.

This is dependent on the following PR being released:
https://github.com/Baseflow/flutter-geolocator/pull/978

### :arrow_heading_down: What is the current behavior?

Currently when the application goes into background and the OS kills the activity then location streaming stops.

### :new: What is the new behavior (if this is a feature change)?

New options have been introduced on Android that will allow the users to configure the background behaviour allow the service to continue running in the background keeping the activity alive while the location stream is active.

### :boom: Does this PR introduce a breaking change?

A new Android service is introduced which changes the behaviour of the location stream to use the new service but existing apps will not know about this change.

### :bug: Recommendations for testing

Testing the normal mode to validate the location stream is still working as expected and testing the background mode with the application running in the background.

### :memo: Links to relevant issues/docs

https://github.com/Baseflow/flutter-geolocator/issues/948
https://github.com/Baseflow/flutter-geolocator/issues/53

### :thinking: Checklist before submitting

- [X] I made sure all projects build.
- [X] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [X] I updated the relevant documentation.
- [X] I rebased onto current `master`.

2022-02-13 18:38 UTC, mvanbeusekom requested changes
To be able to publish this update we should:

[ ] Update the version number in the `pubspec.yaml`;
[ ] Add release note the the `CHANGELOG.md`;
[ ] Update the example App to include new changes;
[ ] Add documentation on how to use the new background services in the `README.md` file.

P.S. I would also like to add the iOS changes you made. They seemed really useful. If you don't have the time, do you mind if I copy it and create a PR my self?

2022-02-13 18:38 UTC, mvanbeusekom commented on geolocator/pubspec.yaml
> +  geolocator_platform_interface: ^4.0.0+1
Version 4.0.0+1 doesn't exists, this should probably be updated to version 4.0.3.
```suggestion
  geolocator_platform_interface: ^4.0.3
```

2022-02-13 18:55 UTC, Wackymax commented
> To be able to publish this update we should:
> 
> * [x]  Update the version number in the `pubspec.yaml`;
> * [x]  Add release note the the `CHANGELOG.md`;
> * [ ]  Update the example App to include new changes;
> * [ ]  Add documentation on how to use the new background services in the `README.md` file.
> 
> P.S. I would also like to add the iOS changes you made. They seemed really useful. If you don't have the time, do you mind if I copy it and create a PR my self?

The changes have been applied. I only updated the readme, the example app does not set any settings for Apple or Android at the moment. In terms of the iOS changes, I don't mind bringing them in. I would be happy to help out there if you feel like it will add value to the library.

2022-02-13 19:03 UTC, mvanbeusekom commented
That would be great. I would like to merge the iOS changes first (in a separate PR) and then update this PR to include the updated geolocator_Apple package as well. 

That way we can release everything in one go.

2022-02-13 19:17 UTC, Wackymax commented
> That would be great. I would like to merge the iOS changes first (in a separate PR) and then update this PR to include the updated geolocator_Apple package as well.
> 
> That way we can release everything in one go.

[982](https://github.com/Baseflow/flutter-geolocator/pull/982) has been created with the iOS changes.

2022-02-13 21:42 UTC, mvanbeusekom commented
@Wackymax just released version 2.1.1 of the geolocator_apple package (thanks for that). 

Could you update this PR to reference this new version of the package and maybe add a little bit of documentation regarding the new parameter to the README.md file?

2022-02-14 04:59 UTC, Wackymax commented
> @Wackymax just released version 2.1.1 of the geolocator_apple package (thanks for that).
> 
> Could you update this PR to reference this new version of the package and maybe add a little bit of documentation regarding the new parameter to the README.md file?

This branch has been updated with the Apple settings changes.

2022-02-14 05:26 UTC, Wackymax commented
@mvanbeusekom it seems like something in the iOS 2.1.1 release is broken. I am not entirely sure what or how to fix it though  🤔

2022-02-14 06:04 UTC, mvanbeusekom commented
I will have a look in an hour or so when I am behind my desk.

2022-02-14 07:15 UTC, Wackymax commented
I have not confirmed this with the published package but it seems like the published iOS may be breaking the official geolocator package as well because we aren't pinning versions in this package. Maybe we should remove the ^ on the platform packages to prevent them from getting upgraded automatically?

2022-02-14 07:48 UTC, mvanbeusekom commented
> I have not confirmed this with the published package but it seems like the published iOS may be breaking the official geolocator package as well because we aren't pinning versions in this package. Maybe we should remove the ^ on the platform packages to prevent them from getting upgraded automatically?

There is indeed a strange issue, I am currently investigating more detailed.

We should not remove the `^` symbol as in many cases we would like to silently release fixes to the platform specific packages without having users to update the `geolocator` plugin it self.

2022-02-14 07:58 UTC, mvanbeusekom commented
So something strange is happening. Somehow the `.h` and `.m` files in the `ios` and `macos` folders (which are all symbolic links to the matching file in the `apple` folder lost their link attribute. 

This means that now they are just files containing a string similar to this:
```
../../../apple/Classes/Handlers/PermissionHandler.m
```

This is of course resulting in a compile error as this is not valid Objective-C code.

2022-02-14 07:59 UTC, mvanbeusekom commented
(sorry, closed the PR by accident)

2022-02-14 08:50 UTC, mvanbeusekom commented
I think I know what happend, I have published the `geolocator_apple` package from a Windows machine (as that is what I had close at hand yesterday). 

I didn't realise this would delete all symbolic links when publishing to pub.dev. I will publish a hotfix now using macOS machine which should fix the issue. 

Note to self: never publish Apple stuff from a Windows machine.

2022-02-14 09:17 UTC, mvanbeusekom approved these changes
LGTM, thanks again for all the work @Wackymax, really appreciate it.

I will merge and release the update today. Do you mind if I mention you in a tweet announcing the update (and do you have a twitter handle)?

2022-02-14 09:17 UTC, merged

2022-02-14 11:23 UTC, Wackymax commented
Wow that is such a bizarre issue 😅. Glad you found it!

Thanks that is pretty awesome! It was really fun contributing, will definitely contribute again when I see use case. My twitter handle is @HennieBrink3