Clear stream before emitting error
Baseflow/flutter-geolocator pull request #998
Opened 2022-03-04 05:16 UTC by zbarbuto

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Bug fix

### :arrow_heading_down: What is the current behavior?

When the location stream times out, if your handler for this error is to immediately re-try listening to the stream, you receive a dead stream.

### :new: What is the new behavior (if this is a feature change)?

Clear out the stale stream before throwing the error so re-listening will get a fresh stream.

### :boom: Does this PR introduce a breaking change?

No

### :bug: Recommendations for testing

Something along these lines (but force it to timeout)

```dart
void _setupLocationStream() {
  final stream = Geolocator.getPositionStream(
    locationSettings: LocationSettings(timeLimit: Duration(seconds: 3))
  );
  locationSubscription = stream.listen((location) {
    print(location);
  });
   locationSubscription!.onError((error) {
     // This attempt to re-setup the stream will get the already timed out stream, meaning
     // you do not get any more updates.
     // If you await a Future.delayed(Duration(milliseconds: 100)); here, you do get updates
     _setupLocationStream();
   });
}
```

### :memo: Links to relevant issues/docs

Specifically [this check](https://github.com/NextFaze/flutter-geolocator/blob/master/geolocator_platform_interface/lib/src/implementations/method_channel_geolocator.dart#L156-L158) is not null because the call to check if the existing stream is null fails (verified with breakpoints)

### :thinking: Checklist before submitting

- [x] I made sure all projects build.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md)).
- [ ] I updated the relevant documentation.
- [x] I rebased onto current `master`.

2022-03-04 09:39 UTC, mvanbeusekom requested changes
Hi @zbarbuto,

Thank you for this contribution, good catch. 

Could you also provide a unit test that proves the previous situation is broken and this fix resolves the issue? That will help us to prevent the same bug in the future.

2022-03-04 09:39 UTC, mvanbeusekom commented on geolocator_platform_interface/CHANGELOG.md
> +- Fix listening location to stream immediately on error
We try to write change log entries starting with a third person singular verb. How about something like:

```suggestion
- Fixes a bug where listening to the position stream immediately after an error, results in listening to a dead stream. 
```

2022-03-06 22:34 UTC, zbarbuto commented on geolocator_platform_interface/CHANGELOG.md
> +- Fix listening location to stream immediately on error
Done, thanks

2022-03-06 22:37 UTC, zbarbuto commented
Have added a test and squashed commits as cleanup.

Sorry the test is a bit clumsy, was a bit complex to reproduce the issue without the fix in testing environment.

2022-03-08 09:28 UTC, mvanbeusekom approved these changes
LGTM, thanks again for this contribution

2022-03-08 09:29 UTC, merged